project:
  type: website

website:
  description: "A blog built with Quarto"
  title: "My Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    code-fold: true
    code-tools: true
    toc: true



