project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://maitreyasuin.github.io/blog
  title: "Maitreya - Notes"
  navbar:
    left:
      - fundamentals.qmd
      - llm-systems.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/maitreyasuin/blog

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    code-fold: true
    code-tools: true
    toc: true



