{
  "hash": "d60f8ec295243322ff5ce15a19e9d5fd",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"A Small Model Is a Budget, Not a Parameter Count\"\ndescription: \"At small scale, parameter count hides the decisions that determine the model you actually deploy: vocabulary, KV state, depth, width, and active versus resident weights. This post derives those budgets from scratch, measures the tokenizer trade-off, and benchmarks equal-size models with a real KV-cached decode path.\"\ncategories: [llm-systems, small-models, architecture]\ndate: 2026-10-22\ndepth: \"Deep dive\"\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  freeze: auto\n---\n\n\"A 135M model\" is not a deployment specification.\n\nIt tells you how many learned scalars exist. It does **not** tell you where they were spent, how much state accumulates for every token in the context, or how many serial stages every generated token has to cross.\n\nAt small scale, those omissions matter. A vocabulary matrix can consume half the model. Changing the number of KV heads can change cache size by multiples without changing the hidden width. Two models with essentially the same parameter count can put very different amounts of work on the critical path of autoregressive decoding.\n\nThat is the theme of this chapter: **treat the parameter count as a budget, then ask where the budget went.**\n\nWe will keep three ledgers separate as we go:\n\n1. **weights** — what has to be trained and stored,\n2. **per-token state** — especially the KV cache that grows with context,\n3. **runtime shape** — how the work is arranged into serial stages and hardware-facing matrix shapes.\n\nMixing those ledgers is how otherwise sensible architectural arguments go wrong.\n\n> **TL;DR** — Start with the budget equation. At `V = 128,256` and `d = 576`, a tied vocabulary matrix alone is **54.7%** of a 135M-parameter budget; changing `n_kv` from 9 to 1 cuts the KV cache for the same model width by **9×**. A larger vocabulary then gives some of that cost back by shortening the sequence, but not for free: it also makes the output projection larger. Finally, equal-size depth/width variants separate in real KV-cached decode latency even though the parameter count barely moves. The count is useful. The allocation is what determines the machine.\n\nThe experiments are deliberately CPU-sized. Exact timings are hardware-dependent; the code prints the numbers for the machine that actually executes the post.\n\n::: {#731610a4 .cell execution_count=1}\n``` {.python .cell-code}\nimport collections\nimport math\nimport os\nimport re\nimport statistics\nimport sysconfig\nimport time\n\nimport torch\nimport torch.nn as nn\nimport torch.nn.functional as F\n\ntorch.manual_seed(0)\nprint(\"torch\", torch.__version__)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntorch 2.8.0\n```\n:::\n:::\n\n\n---\n\n# Act I — start with the ledger\n\n## What exactly are we counting?\n\nBefore benchmarking anything, count the model.\n\nTake a decoder-only transformer with:\n\n- model width `d`,\n- `L` transformer blocks,\n- `n_q` query heads,\n- `n_kv` key/value heads,\n- head dimension `d_h = d / n_q`,\n- a SwiGLU feed-forward network of width `d_ff`,\n- one **tied** input/output vocabulary matrix of shape `V × d`.\n\nI will use bias-free linear layers below. The compact formula also omits the small RMSNorm scale vectors and assumes no learned positional embedding, so treat it as a budget equation rather than an exact `sum(p.numel())`.\n\n### Attention first\n\nThe query projection has shape\n\n$$\nW_Q \\in \\mathbb{R}^{d \\times (n_q d_h)}.\n$$\n\nBecause `n_q d_h = d`, it contains `d²` parameters.\n\nThe output projection is another `d²`.\n\nKeys and values are where the design freedom is. In ordinary multi-head attention every query head gets its own key/value head, so `n_kv = n_q`. Grouped-query attention lets several query heads *share* one key/value head, and multi-query attention takes that to its limit with `n_kv = 1`. The parameter saving is modest; the cache and memory-bandwidth savings are much larger, which is the main systems motivation — and it is why `n_kv` deserves its own symbol rather than being folded into `n_q`.\n\nEach K/V matrix has shape\n\n$$\nW_K, W_V \\in \\mathbb{R}^{d \\times (n_{kv}d_h)}.\n$$\n\nDefine\n\n$$\nr = \\frac{n_{kv}}{n_q}.\n$$\n\nSince `n_kv d_h = r d`, each K/V matrix has `r d²` parameters. Therefore\n\n$$\nP_{\\text{attn, layer}}\n= d^2 + d^2 + r d^2 + r d^2\n= 2d^2(1+r).\n$$\n\nA SwiGLU MLP has three matrices — gate, up, and down — giving\n\n$$\nP_{\\text{MLP, layer}} = 3 d\\,d_{\\mathrm{ff}}.\n$$\n\nWhich raises the question of what `d_ff` should be, and explains a constant that otherwise looks arbitrary. A conventional two-matrix feed-forward network at the usual width `4d` costs\n\n$$\nd(4d) + (4d)d = 8d^2.\n$$\n\nSwiGLU has three matrices instead of two, so matching that budget means\n\n$$\n3 d\\, d_{\\mathrm{ff}} = 8 d^2 \\quad\\Longrightarrow\\quad d_{\\mathrm{ff}} = \\tfrac{8}{3} d.\n$$\n\nThat is the origin of the familiar `8d/3` rule: it gives a three-matrix SwiGLU roughly the same parameter budget as a conventional two-matrix `4d` FFN. Real architectures often round it to something kernel-friendly or move away from it deliberately, so treat it as a reference point rather than a law — but when you see a number near `8d/3` in a config, this is why.\n\nPut the blocks and tied vocabulary matrix together:\n\n$$\n\\boxed{\nP \\approx Vd\n+ L\\left[2d^2(1+r)+3d\\,d_{\\mathrm{ff}}\\right]\n},\n\\qquad\nr=\\frac{n_{kv}}{n_q}.\n$$\n\nA compact derivation is exactly where I like to write the explicit count once. It catches missing factors before they get copied into every later spreadsheet.\n\n::: {#84dd6c9e .cell execution_count=2}\n``` {.python .cell-code}\nd, n_q, n_kv = 576, 9, 3\nd_h = d // n_q\nr = n_kv / n_q\n\nexplicit = (\n    d * (n_q * d_h)        # W_Q\n    + d * (n_kv * d_h)     # W_K\n    + d * (n_kv * d_h)     # W_V\n    + (n_q * d_h) * d      # W_O\n)\nformula = 2 * d * d * (1 + r)\n\nprint(f\"head dimension                    : {d_h}\")\nprint(f\"explicit Q + K + V + O parameters : {explicit:,}\")\nprint(f\"formula  2d²(1+r)                 : {int(formula):,}\")\nprint(f\"match                              : {explicit == int(formula)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nhead dimension                    : 64\nexplicit Q + K + V + O parameters : 884,736\nformula  2d²(1+r)                 : 884,736\nmatch                              : True\n```\n:::\n:::\n\n\nThere is a second ledger that parameter count does not show at all.\n\n## The KV cache is state, not weights\n\nDuring autoregressive generation we do not want to recompute keys and values for the whole prefix at every step. Each layer therefore stores the previous keys and values.\n\nFor one token, one layer stores\n\n- `n_kv × d_h` values for K,\n- `n_kv × d_h` values for V.\n\nAcross all layers:\n\n$$\n\\boxed{\n\\text{KV bytes/token}\n=\n2L\\,n_{kv}\\,d_h\\,b\n}\n$$\n\nwhere `b` is bytes per stored scalar.\n\nThat equation is worth reading literally. `n_q` determines how many query heads do work **now**. `n_kv` determines how many K/V streams survive into the cache for **every future token**.\n\nHere is the same `d = 576`, `L = 30` model under multi-head attention, GQA, and MQA. We hold `d_h = 64` fixed and change only how many distinct K/V heads are stored.\n\n::: {#ce24c3b2 .cell execution_count=3}\n``` {.python .cell-code}\nL, d, n_q, d_h = 30, 576, 9, 64\nBYTES = 2  # bf16/fp16-sized cache\n\nprint(f\"{'attention':<10}{'n_kv':>6}{'KV KiB/token':>15}\")\nfor name, n_kv_ in [(\"MHA\", 9), (\"GQA\", 3), (\"MQA\", 1)]:\n    kv_bytes = 2 * L * n_kv_ * d_h * BYTES\n    print(f\"{name:<10}{n_kv_:>6}{kv_bytes/1024:>15.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nattention   n_kv   KV KiB/token\nMHA            9           67.5\nGQA            3           22.5\nMQA            1            7.5\n```\n:::\n:::\n\n\nSame hidden width. Same number of query heads. **9×** between the two ends of the cache ledger.\n\nThis is the first practical lesson: if a long-context deployment is memory-constrained, `n_kv` is not a cosmetic attention hyperparameter.\n\n---\n\n# Act II — the tokenizer spends from more than one budget\n\n## The vocabulary matrix is not small-model overhead\n\nNow look at the `Vd` term.\n\nIt is a flat charge: you pay it before adding a single transformer block. With tied embeddings, those parameters serve two roles:\n\n1. lookup rows to turn token IDs into hidden vectors,\n2. the output projection that turns the final hidden vector back into `V` logits.\n\nWeight tying saves parameters; it does **not** remove the `d × V` output computation at decode time. Keep that distinction in mind — it matters later.\n\nFirst, just look at capacity.\n\n::: {#48103b02 .cell execution_count=4}\n``` {.python .cell-code}\ndef budget(V, d, L, n_q, n_kv, d_ff, tied=True):\n    \"\"\"Approximate parameter ledger.\n\n    Omits RMSNorm scales and any router/positional parameters. Linear layers in\n    the toy models are bias-free, so no bias terms are missing.\n    \"\"\"\n    vocab = V * d * (1 if tied else 2)\n    blocks = L * (\n        2 * d * d * (1 + n_kv / n_q)\n        + 3 * d * d_ff\n    )\n    return vocab, blocks, vocab + blocks\n\n\nTARGET = 135e6\nd, n_q, n_kv, d_ff = 576, 9, 3, 1536\nper_layer = 2 * d * d * (1 + n_kv / n_q) + 3 * d * d_ff\n\nprint(f\"budget {TARGET/1e6:.0f}M, d={d}, one block costs {per_layer/1e6:.2f}M\\n\")\nprint(f\"{'vocabulary':>12}{'V×d':>12}{'budget %':>11}{'left for blocks':>18}{'whole blocks':>14}\")\n\nfor V_ in [8_192, 32_000, 50_257, 128_256, 202_048]:\n    vocab = V_ * d\n    left = TARGET - vocab\n    print(\n        f\"{V_:>12,}\"\n        f\"{vocab/1e6:>11.1f}M\"\n        f\"{vocab/TARGET:>10.1%}\"\n        f\"{left/1e6:>17.1f}M\"\n        f\"{max(0, int(left // per_layer)):>14}\"\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nbudget 135M, d=576, one block costs 3.54M\n\n  vocabulary         V×d   budget %   left for blocks  whole blocks\n       8,192        4.7M      3.5%            130.3M            36\n      32,000       18.4M     13.7%            116.6M            32\n      50,257       28.9M     21.4%            106.1M            29\n     128,256       73.9M     54.7%             61.1M            17\n     202,048      116.4M     86.2%             18.6M             5\n```\n:::\n:::\n\n\nThe 32k-to-128k move is the important row pair. At this width:\n\n- `V = 32,000` spends 13.7% of the 135M budget on the tied vocabulary matrix;\n- `V = 128,256` spends 54.7%;\n- the remaining block budget falls by enough to remove **fifteen complete transformer blocks**.\n\nAt `V = 202,048`, only about 18.6M parameters remain for the transformer stack — five blocks with this configuration. That is still a language model; it is simply an extremely shallow allocation of a 135M budget.\n\nThe effect gets smaller as the model gets larger, but it does not magically disappear. For a concrete comparison, if a 7B model had `d = 4096`, the same tied 32k and 128k matrices would be about 131M and 525M parameters — roughly 1.9% and 7.5% of 7B. The *fraction* is much smaller than in the 135M example.\n\n### What if we untie input and output embeddings?\n\nAt the small-model end, this can consume the budget before the transformer gets a chance.\n\n::: {#eab6e029 .cell execution_count=5}\n``` {.python .cell-code}\nV, d = 128_256, 576\none = V * d\n\nprint(f\"one V×d matrix             : {one/1e6:>7.1f}M\")\nprint(f\"two untied matrices        : {2*one/1e6:>7.1f}M\")\nprint(f\"reference model budget     : {135:>7.1f}M\")\nprint(f\"two matrices exceed budget : {2*one > 135e6}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\none V×d matrix             :    73.9M\ntwo untied matrices        :   147.8M\nreference model budget     :   135.0M\ntwo matrices exceed budget : True\n```\n:::\n:::\n\n\nThe precise statement matters. Untying does not make the architecture impossible; it makes it **larger**. Starting from the tied configuration, the second matrix adds another 73.9M parameters. If 135M is a hard storage or training budget, that choice is simply unavailable unless something else shrinks.\n\nThat is why tokenization is an architectural decision in a small model.\n\nBut that is only one side of it.\n\n## A larger vocabulary buys shorter sequences\n\nThe obvious response is: make `V` small.\n\nThat saves weights, but usually makes the same text longer in tokens. Longer sequences cost prefill work, attention work, and KV cache. So we need to measure the other side of the trade instead of arguing about it abstractly.\n\nWe can build enough BPE from scratch to see the effect.\n\n### First, choose a corpus\n\nFor a self-contained experiment, use Python source code already installed with the interpreter:\n\n::: {#0d39f8ad .cell execution_count=6}\n``` {.python .cell-code}\ndef load_corpus(n_chars=400_000):\n    \"\"\"Collect a deterministic-sized slice of local Python stdlib source.\"\"\"\n    root = sysconfig.get_paths()[\"stdlib\"]\n    parts, total = [], 0\n\n    for dirpath, dirnames, files in os.walk(root):\n        dirnames.sort()          # os.walk order is filesystem-dependent; pin it\n        for filename in sorted(files):\n            if not filename.endswith(\".py\"):\n                continue\n            path = os.path.join(dirpath, filename)\n            try:\n                piece = open(path, encoding=\"utf-8\").read()\n            except (OSError, UnicodeError):\n                continue\n\n            parts.append(piece)\n            total += len(piece)\n\n        if total > n_chars * 1.5:\n            break\n\n    return \"\\n\".join(parts)[:n_chars]\n\n\ncorpus = load_corpus()\nprint(f\"corpus: {len(corpus)/1e3:.0f}k characters of Python source\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncorpus: 400k characters of Python source\n```\n:::\n:::\n\n\nThe exact source files depend on the Python installation, so the exact compression numbers are not a benchmark. The controlled variable is the vocabulary size **within one render**.\n\n### Then build a minimal BPE\n\nProduction tokenizers have more machinery: normalization, a pre-tokenizer, special tokens, byte fallback, and carefully chosen training data. We do not need all of that to isolate the vocabulary/compression trade-off.\n\nOne detail *does* matter: every input character must be represented.\n\nA tempting shortcut is `text.split(\" \")`. Do not do that here. The spaces disappear from the symbol sequences, and if you still divide `len(text)` by the resulting token count, the reported characters/token is inflated.\n\nInstead, split into whitespace runs and non-whitespace runs. Every character remains in exactly one piece, then BPE merges only within a piece.\n\n::: {#34cbd4dd .cell execution_count=7}\n``` {.python .cell-code}\ndef train_bpe(text, vocab_size):\n    \"\"\"A small character-level BPE with incremental pair counts.\n\n    Pretokenization preserves *all* characters:\n      \"x = 10\\n\" -> [\"x\", \" \", \"=\", \" \", \"10\", \"\\n\"]\n\n    BPE then repeatedly merges the most frequent adjacent symbol pair inside\n    each piece. We stop if the best remaining pair occurs fewer than twice.\n    \"\"\"\n\n    # Counter compresses repeated pieces, so we do not process every occurrence\n    # separately during every merge.\n    pieces = collections.Counter(re.findall(r\"\\s+|[^\\s]+\", text))\n    seqs = {piece: tuple(piece) for piece in pieces}\n    vocab = {ch for piece in pieces for ch in piece}\n\n    # pairs[p] = corpus frequency of adjacent pair p.\n    # where[p] = unique pieces whose symbol sequence currently contains p.\n    pairs = collections.Counter()\n    where = collections.defaultdict(set)\n\n    for piece, count in pieces.items():\n        symbols = seqs[piece]\n        for i in range(len(symbols) - 1):\n            pair = (symbols[i], symbols[i + 1])\n            pairs[pair] += count\n            where[pair].add(piece)\n\n    while len(vocab) < vocab_size and pairs:\n        best = max(pairs, key=pairs.get)\n\n        # This is our choice, not a law of BPE: do not spend vocabulary on a\n        # merge seen only once in the training corpus.\n        if pairs[best] < 2:\n            break\n\n        merged_symbol = best[0] + best[1]\n        vocab.add(merged_symbol)\n\n        # Only pieces containing `best` can change. This inverted index is what\n        # avoids rescanning the entire corpus after every merge.\n        for piece in list(where[best]):\n            symbols = seqs[piece]\n            count = pieces[piece]\n\n            # 1) retract this piece's old pair contributions\n            for i in range(len(symbols) - 1):\n                pair = (symbols[i], symbols[i + 1])\n                pairs[pair] -= count\n                if pairs[pair] <= 0:\n                    pairs.pop(pair, None)\n                    where.pop(pair, None)\n                else:\n                    where[pair].discard(piece)\n\n            # 2) apply the selected merge left-to-right\n            out, i = [], 0\n            while i < len(symbols):\n                if i < len(symbols) - 1 and (symbols[i], symbols[i + 1]) == best:\n                    out.append(merged_symbol)\n                    i += 2\n                else:\n                    out.append(symbols[i])\n                    i += 1\n\n            symbols = tuple(out)\n            seqs[piece] = symbols\n\n            # 3) add the new pair contributions back\n            for i in range(len(symbols) - 1):\n                pair = (symbols[i], symbols[i + 1])\n                pairs[pair] += count\n                where[pair].add(piece)\n\n        pairs.pop(best, None)\n        where.pop(best, None)\n\n    n_tokens = sum(len(seqs[piece]) * count for piece, count in pieces.items())\n    chars_per_token = len(text) / n_tokens\n    return len(vocab), chars_per_token\n```\n:::\n\n\nThe algorithm is simple; the implementation detail worth remembering is the `where` index. A naive trainer recounts every pair in the entire corpus after every merge. Here, a merge only revisits pieces that actually contained the selected pair.\n\nNow vary only the requested vocabulary:\n\n::: {#c47a5975 .cell execution_count=8}\n``` {.python .cell-code}\nt0 = time.time()\ncompression = {}\n\nfor requested_V in [256, 512, 1024, 2048, 4096, 8192]:\n    actual_V, cpt = train_bpe(corpus, requested_V)\n    compression[actual_V] = cpt\n    print(\n        f\"requested V = {requested_V:>5}   \"\n        f\"actual V = {actual_V:>5}   \"\n        f\"{cpt:.3f} characters/token\"\n    )\n\nprint(f\"\\n[{time.time() - t0:.1f}s]\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrequested V =   256   actual V =   256   2.032 characters/token\nrequested V =   512   actual V =   512   2.457 characters/token\nrequested V =  1024   actual V =  1024   2.884 characters/token\nrequested V =  2048   actual V =  2048   3.327 characters/token\nrequested V =  4096   actual V =  4096   3.773 characters/token\nrequested V =  8192   actual V =  8192   4.201 characters/token\n\n[8.7s]\n```\n:::\n:::\n\n\nThe exact numbers depend on the local stdlib corpus, but the direction is the point: a larger vocabulary spends more parameters to represent the same character stream with fewer tokens.\n\nWhy does that matter beyond the cache? If a fixed piece of text becomes `N` tokens, the projection/MLP work is roughly linear in `N`, while the attention-score part of a full prefill grows roughly with `N²`. The exact runtime is kernel- and hardware-dependent, but token count enters more than one term of the serving bill.\n\nThere is also a useful failure mode hidden here. If we ask this small corpus for a much larger vocabulary, our `frequency >= 2` rule eventually refuses to add more merges:\n\n::: {#02545bfb .cell execution_count=9}\n``` {.python .cell-code}\nrequested = 16_384\nactual, cpt = train_bpe(corpus, requested)\nprint(f\"requested vocabulary : {requested:,}\")\nprint(f\"actual vocabulary    : {actual:,}\")\nprint(f\"characters/token     : {cpt:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrequested vocabulary : 16,384\nactual vocabulary    : 8,803\ncharacters/token     : 4.256\n```\n:::\n:::\n\n\nDo not turn that into the false rule that \"BPE cannot build a larger vocabulary.\" A production trainer can keep adding rare or even one-off merges if configured to do so. What the early stop tells us is narrower and more useful: **the corpus no longer provides repeated evidence for spending additional vocabulary under our rule.**\n\n## The vocabulary decision hits two ledgers — and latency sees both\n\nNow hold the transformer stack fixed and convert the sequence-length effect into memory.\n\n::: {#c9f059a0 .cell execution_count=10}\n``` {.python .cell-code}\nd, L, n_q, n_kv, d_ff = 576, 30, 9, 3, 1536\nd_h = d // n_q\nBYTES = 2  # bf16-sized weights/cache for this accounting example\n\nkv_per_token = 2 * L * n_kv * d_h * BYTES\n_, block_params, _ = budget(0, d, L, n_q, n_kv, d_ff)\n\nprint(f\"KV cache : {kv_per_token:,} bytes/token = {kv_per_token/1024:.1f} KiB/token\")\nprint(f\"blocks   : {block_params/1e6:.1f}M parameters = \"\n      f\"{block_params * BYTES / 1e6:.0f} MB\\n\")\n\nfor chars in [20_000, 2_000_000]:\n    print(f\"context: {chars:,} characters\")\n    print(\n        f\"  {'V':>7}{'chars/tok':>11}{'tokens':>10}\"\n        f\"{'V×d MB':>10}{'KV MB':>11}{'accounted':>11}\"\n    )\n\n    for V_, cpt in compression.items():\n        tokens = chars / cpt\n        vocab_mb = V_ * d * BYTES / 1e6\n        kv_mb = tokens * kv_per_token / 1e6\n        blocks_mb = block_params * BYTES / 1e6\n\n        print(\n            f\"  {V_:>7}\"\n            f\"{cpt:>11.3f}\"\n            f\"{tokens:>10.0f}\"\n            f\"{vocab_mb:>10.1f}\"\n            f\"{kv_mb:>11.1f}\"\n            f\"{vocab_mb + kv_mb + blocks_mb:>12.1f}\"\n        )\n    print()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nKV cache : 23,040 bytes/token = 22.5 KiB/token\nblocks   : 106.2M parameters = 212 MB\n\ncontext: 20,000 characters\n        V  chars/tok    tokens    V×d MB      KV MB  accounted\n      256      2.032      9843       0.3      226.8       439.4\n      512      2.457      8140       0.6      187.6       400.5\n     1024      2.884      6934       1.2      159.8       373.3\n     2048      3.327      6011       2.4      138.5       353.2\n     4096      3.773      5301       4.7      122.1       339.2\n     8192      4.201      4761       9.4      109.7       331.5\n\ncontext: 2,000,000 characters\n        V  chars/tok    tokens    V×d MB      KV MB  accounted\n      256      2.032    984280       0.3    22677.8     22890.4\n      512      2.457    814035       0.6    18755.4     18968.3\n     1024      2.884    693385       1.2    15975.6     16189.1\n     2048      3.327    601080       2.4    13848.9     14063.6\n     4096      3.773    530085       4.7    12213.2     12430.2\n     8192      4.201    476080       9.4    10968.9     11190.7\n\n```\n:::\n:::\n\n\nThe last column is named `accounted` rather than `total` deliberately. It is exactly three terms — block weights, vocabulary weights, KV cache — and nothing else. Activation buffers, attention workspaces, allocator fragmentation and framework overhead are all real and all absent. Measure a subset, name the subset; a column labelled \"total\" invites the reader to compare it against a number from `nvidia-smi` and conclude that the arithmetic is wrong.\n\nFor long contexts the cache dominates this particular configuration, so paying a few extra megabytes for the vocabulary matrix can save far more memory by reducing the number of cached tokens.\n\nBut \"larger vocabulary wins\" is still too broad. There is a crossover.\n\nThe extra vocabulary weight is paid once. KV savings accumulate with every character of context. For the smallest and largest vocabulary in our table, solve for the context length where those two terms are equal:\n\n::: {#d57724ec .cell execution_count=11}\n``` {.python .cell-code}\nsmall_V = min(compression)\nlarge_V = max(compression)\n\nsmall_cpt = compression[small_V]\nlarge_cpt = compression[large_V]\n\nextra_vocab_bytes = (large_V - small_V) * d * BYTES\nkv_bytes_saved_per_char = kv_per_token * (1 / small_cpt - 1 / large_cpt)\ncrossover_chars = extra_vocab_bytes / kv_bytes_saved_per_char\n\nprint(f\"compare V={small_V} -> V={large_V}\")\nprint(f\"extra vocabulary memory : {extra_vocab_bytes/1e6:.2f} MB\")\nprint(f\"KV saved per character  : {kv_bytes_saved_per_char/1024:.2f} KiB\")\nprint(f\"memory crossover        : about {crossover_chars:,.0f} characters\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncompare V=256 -> V=8192\nextra vocabulary memory : 9.14 MB\nKV saved per character  : 5.72 KiB\nmemory crossover        : about 1,562 characters\n```\n:::\n:::\n\n\nThat is a much better way to reason about the choice than declaring one vocabulary \"efficient.\"\n\nAnd memory is still not latency.\n\nA larger vocabulary has two opposing runtime effects:\n\n- **fewer tokens** can reduce prefill work, attention work, KV traffic, and the number of autoregressive steps needed to emit a fixed amount of text;\n- **more logits** make the tied output projection `h @ Eᵀ`, with `E ∈ R^{V×d}`, larger at every generated token.\n\nSo the vocabulary choice has to be made against the workload. Long-context memory may favor compression aggressively. A tight per-token decode target may care about the vocabulary projection. We will come back to that projection after the next experiment.\n\n---\n\n# Act III — same parameter count, different critical path\n\n### And memory is still not latency\n\nOne consequence has been waiting since the first table in this Act, and it is the moment the parameter ledger reaches across into the runtime one.\n\n::: {#46f6c10f .cell execution_count=12}\n``` {.python .cell-code}\nV_big = 128_256\nhead = V_big * d\nblock_budget = TARGET - head\nwhole_blocks = int(block_budget // per_layer)\n\nprint(f\"vocabulary matrix   : {head/1e6:>6.1f}M weights\")\nprint(f\"budget for blocks   : {block_budget/1e6:>6.1f}M weights\")\nprint(f\"ratio               : {head/block_budget:>6.2f}x\")\nprint(f\"blocks actually fit : {whole_blocks}, using {whole_blocks*per_layer/1e6:.1f}M\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nvocabulary matrix   :   73.9M weights\nbudget for blocks   :   61.1M weights\nratio               :   1.21x\nblocks actually fit : 17, using 60.2M\n```\n:::\n:::\n\n\nBecause the embedding is tied, that same matrix is the output projection. So at every decode step this model performs one `d × V` matrix-vector product against a matrix **larger than the entire budget left for transformer blocks**.\n\nWhich inverts how it looked a moment ago. In the parameter ledger the vocabulary matrix reads as overhead — a lookup table crowding out real layers. For one decoded token it is the largest individual learned dense projection in the model. Both descriptions are of the same 73.9M numbers.\n\nBe precise about the scope of that: it is a claim about *dense learned projections*. Attention against the cached prefix is separate work that grows with context length, and at long enough context it dominates everything. What the arithmetic above establishes is that the matrix you were about to dismiss as embedding overhead is the biggest single weight matrix in the decode path.\n\nWeight tying halves the storage. It does not remove the computation, because you still have to produce a logit for every token in the vocabulary before you can sample one.\n\nSo follow one vocabulary decision through all three ledgers. In Act II, moving from a 32k vocabulary to a 128k one was a **weight tax** — at this width it cost fifteen complete transformer blocks. The BPE experiment then showed what that buys: **shorter sequences**, with a calculable context length beyond which the KV savings repay the extra vocabulary memory under this model, corpus and accounting. And now the same matrix appears a third time as **computation**, once per generated token, whatever the sequence length.\n\nThree ledgers, one decision, and no vocabulary size that is optimal in all of them. That is the pattern. Now hold the weight budget fixed and change the shape of the transformer itself.\n\n## Hold the budget fixed and move it between depth and width\n\nThe block term is roughly quadratic in `d`:\n\n$$\nP_{\\text{blocks}} \\propto Ld^2.\n$$\n\nSo at approximately fixed parameters, making a model narrower lets us make it deeper.\n\nThat does **not** imply equal runtime.\n\nDepth creates more sequential stages. Width creates more work inside each stage, which hardware can often exploit in parallel. The trade-off is hardware-dependent, so the right experiment is not another parameter table — it is a timing measurement.\n\nFirst construct four roughly equal-size shapes.\n\nFor this timing experiment I use a smaller 45M budget and `V = 8192` so the CPU run stays practical. I also hold two easy-to-miss confounders fixed:\n\n- head dimension is always `64`,\n- `n_kv / n_q = 1/2` for every shape.\n\nIf we kept the number of heads fixed while changing `d`, head dimension would change too, and part of the latency difference could simply be kernel shape.\n\n::: {#f3aac655 .cell execution_count=13}\n``` {.python .cell-code}\nV_BENCH = 8_192\nTARGET_BENCH = 45e6\n\n\ndef rounded_swiglu_width(d):\n    # A 3-matrix SwiGLU at 8d/3 has approximately the same parameter count\n    # as a conventional 2-matrix FFN at 4d. Round for kernel-friendly shapes.\n    return int(round((8 * d / 3) / 64)) * 64\n\n\ndef nearest_layers(V, d, target, n_q, n_kv, d_ff):\n    return min(\n        range(2, 80),\n        key=lambda L: abs(budget(V, d, L, n_q, n_kv, d_ff)[2] - target),\n    )\n\n\nshape_specs = [\n    (\"wide, shallow\", 768, 12, 6),\n    (\"balanced\", 640, 10, 5),\n    (\"thin, deep\", 512, 8, 4),\n    (\"very thin, deep\", 384, 6, 3),\n]\n\nshapes = []\n\nprint(\n    f\"{'shape':<18}{'d':>6}{'heads':>8}{'kv':>6}\"\n    f\"{'d_ff':>8}{'L':>5}{'params':>11}{'KV KiB/tok':>13}\"\n)\n\nfor name, d_, n_q_, n_kv_ in shape_specs:\n    assert d_ // n_q_ == 64\n    assert n_q_ / n_kv_ == 2\n\n    d_ff_ = rounded_swiglu_width(d_)\n    L_ = nearest_layers(\n        V_BENCH, d_, TARGET_BENCH, n_q_, n_kv_, d_ff_\n    )\n    p = budget(V_BENCH, d_, L_, n_q_, n_kv_, d_ff_)[2]\n\n    shapes.append((name, d_, L_, n_q_, n_kv_, d_ff_, p))\n\n    kv_kib = 2 * L_ * n_kv_ * 64 * 2 / 1024      # the Act I formula, per shape\n\n    print(\n        f\"{name:<18}{d_:>6}{n_q_:>8}{n_kv_:>6}\"\n        f\"{d_ff_:>8}{L_:>5}{p/1e6:>10.1f}M{kv_kib:>13.1f}\"\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nshape                  d   heads    kv    d_ff    L     params   KV KiB/tok\nwide, shallow        768      12     6    2048    6      45.2M          9.0\nbalanced             640      10     5    1728    9      46.2M         11.2\nthin, deep           512       8     4    1344   14      44.1M         14.0\nvery thin, deep      384       6     3    1024   26      45.3M         19.5\n```\n:::\n:::\n\n\nLook at the last column before going further, because it undermines the phrase \"everything else held fixed\" and it is worth being honest about.\n\nHead dimension is fixed at 64 and the GQA ratio at 2, so those are genuinely controlled. But `n_kv` still falls as `d` shrinks — six K/V heads at `d = 768`, three at `d = 384` — while `L` rises from 6 to 26. Run those through `2·L·n_kv·d_h` and **the per-token cache grows from 9.0 to 19.5 KiB, a factor of 2.17.**\n\nSo this is not an isolated measurement of \"what does adding depth cost.\" Equal parameter count does not hold the state ledger fixed, and at any given cache length the deeper models are also doing more attention work and moving more cache traffic per token.\n\nThat is not a flaw in the experiment; it is the point arriving early. These are four whole architectural shapes under *roughly* the same weight budget — and \"roughly\" is doing real work, since the counts span 44.1M to 46.2M rather than landing on a single number. Vocabulary, head dimension and GQA ratio are deliberately controlled. Even so, the state ledger moves: weights stay near 45M while KV per token more than doubles. That is precisely why a parameter count under-determines the model.\n\nThis is an easy place to write a benchmark that looks right but measures the wrong thing.\n\nCalling\n\n```python\nmodel(torch.randint(0, V, (1, 1)))\n```\n\nis a one-token forward pass. It is **not** autoregressive decode after a prompt unless the model also reads the K/V state produced by that prompt.\n\nSo the toy model below has two explicit paths:\n\n- `prefill(...)` processes the whole prompt causally and writes K/V into a cache;\n- `decode_at(...)` processes one new token, appends its K/V at a fixed cache position, and attends to all cached tokens.\n\nThe cache is preallocated. A simple `torch.cat([old_k, new_k], dim=2)` is convenient for a demo, but it copies the prefix on every step and would contaminate the latency measurement with an allocation/copy pattern a production cache avoids.\n\n::: {#573ff07f .cell execution_count=14}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Minimal GQA decoder with an explicit preallocated KV cache\"}\nclass Block(nn.Module):\n    def __init__(self, d, n_q, n_kv, d_ff):\n        super().__init__()\n        assert d % n_q == 0\n        assert n_q % n_kv == 0\n\n        self.n_q = n_q\n        self.n_kv = n_kv\n        self.d_h = d // n_q\n\n        self.wq = nn.Linear(d, n_q * self.d_h, bias=False)\n        self.wk = nn.Linear(d, n_kv * self.d_h, bias=False)\n        self.wv = nn.Linear(d, n_kv * self.d_h, bias=False)\n        self.wo = nn.Linear(n_q * self.d_h, d, bias=False)\n\n        self.gate = nn.Linear(d, d_ff, bias=False)\n        self.up = nn.Linear(d, d_ff, bias=False)\n        self.down = nn.Linear(d_ff, d, bias=False)\n\n        self.n1 = nn.RMSNorm(d)\n        self.n2 = nn.RMSNorm(d)\n\n    def _qkv(self, h):\n        \"\"\"[B,T,d] -> Q:[B,n_q,T,d_h], K/V:[B,n_kv,T,d_h].\"\"\"\n        B, T, _ = h.shape\n\n        q = (\n            self.wq(h)\n            .view(B, T, self.n_q, self.d_h)\n            .transpose(1, 2)\n        )\n        k = (\n            self.wk(h)\n            .view(B, T, self.n_kv, self.d_h)\n            .transpose(1, 2)\n        )\n        v = (\n            self.wv(h)\n            .view(B, T, self.n_kv, self.d_h)\n            .transpose(1, 2)\n        )\n        return q, k, v\n\n    def prefill(self, x, k_cache, v_cache):\n        \"\"\"Process the prompt and populate cache positions [0:T).\"\"\"\n        B, T, _ = x.shape\n\n        h = self.n1(x)\n        q, k, v = self._qkv(h)\n\n        # Cache the *unrepeated* GQA K/V heads. This is the memory counted by\n        # 2 * L * n_kv * d_h bytes/token.\n        k_cache[:, :, :T].copy_(k)\n        v_cache[:, :, :T].copy_(v)\n\n        a = F.scaled_dot_product_attention(\n            q, k, v,\n            is_causal=True,\n            enable_gqa=True,\n        )\n        x = x + self.wo(a.transpose(1, 2).reshape(B, T, -1))\n\n        h = self.n2(x)\n        x = x + self.down(F.silu(self.gate(h)) * self.up(h))\n        return x\n\n    def decode_at(self, x, k_cache, v_cache, pos):\n        \"\"\"Decode one token at cache position `pos`.\n\n        x has T=1. The cache already contains only past positions [0:pos), so\n        after writing the current K/V there are no future keys to mask.\n        \"\"\"\n        B, T, _ = x.shape\n        assert T == 1\n\n        h = self.n1(x)\n        q, k, v = self._qkv(h)\n\n        k_cache[:, :, pos:pos + 1].copy_(k)\n        v_cache[:, :, pos:pos + 1].copy_(v)\n\n        # Important incremental-decoding detail:\n        # q length is 1 while k/v length is pos+1. Since the slice contains\n        # only past+current keys, is_causal=False is correct here.\n        a = F.scaled_dot_product_attention(\n            q,\n            k_cache[:, :, :pos + 1],\n            v_cache[:, :, :pos + 1],\n            is_causal=False,\n            enable_gqa=True,\n        )\n        x = x + self.wo(a.transpose(1, 2).reshape(B, 1, -1))\n\n        h = self.n2(x)\n        x = x + self.down(F.silu(self.gate(h)) * self.up(h))\n        return x\n\n\nclass LM(nn.Module):\n    def __init__(self, V, d, L, n_q, n_kv, d_ff):\n        super().__init__()\n\n        self.emb = nn.Embedding(V, d)\n        self.blocks = nn.ModuleList(\n            [Block(d, n_q, n_kv, d_ff) for _ in range(L)]\n        )\n        self.norm = nn.RMSNorm(d)\n\n    def make_cache(self, batch_size, max_seq_len):\n        caches = []\n        dtype = self.emb.weight.dtype\n        device = self.emb.weight.device\n\n        for block in self.blocks:\n            shape = (\n                batch_size,\n                block.n_kv,\n                max_seq_len,\n                block.d_h,\n            )\n            k_cache = torch.empty(shape, dtype=dtype, device=device)\n            v_cache = torch.empty_like(k_cache)\n            caches.append((k_cache, v_cache))\n\n        return caches\n\n    def prefill(self, idx, caches):\n        h = self.emb(idx)\n\n        for block, (k_cache, v_cache) in zip(self.blocks, caches):\n            h = block.prefill(h, k_cache, v_cache)\n\n        # Serving needs the next-token logits, not a V-dimensional logit vector\n        # for every prompt position.\n        h_last = self.norm(h[:, -1:])\n        return h_last @ self.emb.weight.T\n\n    def decode_at(self, idx, caches, pos):\n        h = self.emb(idx)\n\n        for block, (k_cache, v_cache) in zip(self.blocks, caches):\n            h = block.decode_at(h, k_cache, v_cache, pos)\n\n        return self.norm(h) @ self.emb.weight.T\n```\n:::\n\n\nTwo details in that code are easy to miss in a larger inference engine.\n\nThe `enable_gqa=True` argument requires a recent PyTorch build with SDPA GQA support; the post prints the installed version at the top so a rerun is easy to diagnose.\n\nFirst, GQA does **not** mean storing `n_q` copies of K/V. The cache keeps only `n_kv` heads. The attention kernel handles the grouping.\n\nSecond, `is_causal=True` is right for square prompt self-attention, but incremental decode is different: our one query is allowed to see every key in the cache slice because that slice contains no future positions.\n\nThis timing harness now measures those two paths separately.\n\n::: {#6e4a93e7 .cell execution_count=15}\n``` {.python .cell-code}\ntorch.set_num_threads(4)\n\nPROMPT_LEN = 256\nprompt = torch.randint(0, V_BENCH, (1, PROMPT_LEN))\nnext_token = torch.randint(0, V_BENCH, (1, 1))\n```\n:::\n\n\nBefore timing anything, check that the cached path is *correct*. A KV cache is\nexactly the kind of code that runs, produces plausible numbers, and is quietly\noff by one — and then you have benchmarked the wrong function.\n\nThe test: compute the next-token logits after consuming the same nine tokens in\ntwo different ways. First, prefill all nine at once and read the last position —\nthe teacher-forced answer we trust. Second, prefill the first eight and feed the\nninth through the cached decode path. Both have now consumed the identical\nprefix, so both must predict the tenth token identically.\n\n::: {#3a23e6d8 .cell execution_count=16}\n``` {.python .cell-code}\ntorch.manual_seed(0)\nprobe = LM(V=500, d=64, L=3, n_q=4, n_kv=2, d_ff=128).eval()\nseq = torch.randint(0, 500, (1, 9))\n\nwith torch.no_grad():\n    cache_a = probe.make_cache(batch_size=1, max_seq_len=16)\n    probe.prefill(seq[:, :8], cache_a)                     # positions 0..7\n    from_cache = probe.decode_at(seq[:, 8:9], cache_a, pos=8)\n\n    cache_b = probe.make_cache(batch_size=1, max_seq_len=16)\n    from_full = probe.prefill(seq, cache_b)[:, -1:]        # all 9 at once\n\nprint(f\"max abs difference : {(from_cache - from_full).abs().max():.3e}\")\nprint(f\"logit scale        : {from_full.abs().max():.3f}\")\nprint(f\"agree              : {torch.allclose(from_cache, from_full, atol=1e-4)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmax abs difference : 4.768e-06\nlogit scale        : 61.131\nagree              : True\n```\n:::\n:::\n\n\nAgreement to a few parts in ten million against logits of order 60, which is\nordinary float32 reassociation and not a bug. Now the measurement means\nsomething.\n\n::: {#97afd66d .cell execution_count=17}\n``` {.python .cell-code}\ndef median_ms(fn, reps, warmup=2):\n    \"\"\"Median latency; one scheduler hiccup should not become the result.\"\"\"\n    for _ in range(warmup):\n        fn()\n\n    samples = []\n    for _ in range(reps):\n        t0 = time.perf_counter()\n        fn()\n        samples.append((time.perf_counter() - t0) * 1000)\n\n    return statistics.median(samples)\n\n\nbuilt = {}\nfor name, d_, L_, n_q_, n_kv_, d_ff_, p in shapes:\n    model = LM(\n        V_BENCH, d_, L_, n_q_, n_kv_, d_ff_\n    ).eval()\n    cache = model.make_cache(batch_size=1, max_seq_len=PROMPT_LEN + 1)\n    built[name] = (model, cache, L_, p)\n\npre_runs = {name: [] for name in built}\ndec_runs = {name: [] for name in built}\n\nwith torch.no_grad():\n    # Interleave model order across rounds so slow thermal/scheduler drift is\n    # less likely to masquerade as an architecture difference.\n    items = list(built.items())\n    for round_idx in range(4):          # 4, not 2: the median of two values is\n                                        # just their midpoint, so the outer\n                                        # aggregation would have no robustness\n        # Genuinely alternate direction. Iterating the same order twice and\n        # calling it interleaving does not control for drift; it just averages\n        # two samples taken under the same conditions.\n        order = items if round_idx % 2 == 0 else list(reversed(items))\n        for name, (model, cache, L_, p) in order:\n            pre_runs[name].append(\n                median_ms(\n                    lambda m=model, c=cache: m.prefill(prompt, c),\n                    reps=2,\n                    warmup=1,\n                )\n            )\n\n            # Ensure cache positions [0:PROMPT_LEN) contain this prompt before\n            # timing a step at position PROMPT_LEN.\n            model.prefill(prompt, cache)\n\n            dec_runs[name].append(\n                median_ms(\n                    lambda m=model, c=cache: m.decode_at(\n                        next_token, c, PROMPT_LEN\n                    ),\n                    reps=10,\n                    warmup=2,\n                )\n            )\n\nprint(\n    f\"{'shape':<18}{'params':>10}{'L':>5}\"\n    f\"{'prefill':>12}{'cached decode':>15}\"\n)\n\nrows = []\nfor name, (model, cache, L_, p) in built.items():\n    pre = statistics.median(pre_runs[name])\n    dec = statistics.median(dec_runs[name])\n    rows.append((name, p, L_, pre, dec))\n\n    print(\n        f\"{name:<18}{p/1e6:>9.1f}M{L_:>5}\"\n        f\"{pre:>10.1f} ms{dec:>12.2f} ms\"\n    )\n\nfastest_pre = min(row[3] for row in rows)\nslowest_pre = max(row[3] for row in rows)\nfastest_dec = min(row[4] for row in rows)\nslowest_dec = max(row[4] for row in rows)\n\nprint(f\"\\nprefill spread      : {slowest_pre / fastest_pre:.2f}x\")\nprint(f\"cached-decode spread: {slowest_dec / fastest_dec:.2f}x\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nshape                 params    L     prefill  cached decode\nwide, shallow          45.2M    6      26.1 ms        4.14 ms\nbalanced               46.2M    9      29.7 ms        4.70 ms\nthin, deep             44.1M   14      32.8 ms        5.24 ms\nvery thin, deep        45.3M   26      42.8 ms        6.90 ms\n\nprefill spread      : 1.64x\ncached-decode spread: 1.67x\n```\n:::\n:::\n\n\nDo not memorize the ratio printed by this machine. Read the mechanism.\n\nAll four models are around 45M parameters, yet they do not have the same critical path. The deepest model has many more block boundaries and sequential dependencies. The widest model does more arithmetic inside each block, but presents larger matrix operations to the hardware.\n\nA better shorthand than \"depth is slow, width is fast\" is:\n\n> **Depth adds serial stages. Width adds more parallelizable work inside a stage.**\n\nHow those two effects balance depends on kernels and hardware. That is exactly why parameter count cannot answer a latency question.\n\nThere is also a quality trade-off. MobileLLM reports that, for its roughly 125M/350M experiments, deeper-and-thinner variants generally outperform wider-and-shallower variants at comparable parameter count. That is a useful empirical result — and it makes the systems trade-off more interesting, not less. The architecture that spends the budget best for quality need not be the one that meets a specific latency target.\n\n### What this benchmark still is not\n\nThis is a deliberately small PyTorch-eager CPU benchmark. It has:\n\n- batch size 1,\n- a real preallocated KV cache,\n- no quantization,\n- no fused RoPE,\n- no paged KV allocator,\n- no continuous batching,\n- no compilation or hardware-specific inference engine.\n\nThe model is also untrained; positional encoding is omitted because we are measuring shape, not language quality.\n\nThose are not footnotes to hide. They define what the experiment establishes: **equal parameter counts do not imply equal prefill or cached-decode latency, and the result has to be measured on the target stack.** The exact factor is not portable.\n\n---\n\n# Act IV — two more ways the count lies by omission\n\n## Active parameters are not resident parameters\n\nA mixture-of-experts model makes the word \"size\" ambiguous in another way.\n\nSuppose every layer contains `n_experts` SwiGLU experts but each token routes through only `top_k` of them. Ignoring the small router and norm parameters:\n\n- all expert weights must be **resident** somewhere,\n- only the selected experts are **active** for that token.\n\n::: {#50ba63e2 .cell execution_count=18}\n``` {.python .cell-code}\ndef moe_budget(V, d, L, n_q, n_kv, d_ff, n_experts, top_k):\n    shared_attention = L * 2 * d * d * (1 + n_kv / n_q)\n    one_expert = 3 * d * d_ff\n\n    shared = V * d + shared_attention\n    active = shared + L * top_k * one_expert\n    resident = shared + L * n_experts * one_expert\n\n    return active, resident\n\n\nactive, resident = moe_budget(\n    V=32_000,\n    d=768,\n    L=24,\n    n_q=12,\n    n_kv=4,\n    d_ff=2048,\n    n_experts=16,\n    top_k=2,\n)\n\nprint(f\"active-path parameters : {active/1e6:>8.1f}M\")\nprint(f\"resident parameters    : {resident/1e6:>8.1f}M\")\nprint(f\"resident / active      : {resident/active:>8.2f}x\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nactive-path parameters :    288.8M\nresident parameters    :   1874.3M\nresident / active      :     6.49x\n```\n:::\n:::\n\n\nFor this toy configuration, the active path touches about 289M parameters while roughly 1.87B parameters are resident — a **6.5×** gap.\n\n\"Active parameters\" is still only a compute proxy. An embedding lookup does not multiply through every vocabulary row, the tied output head does, routing has its own cost, and expert implementations differ. But the deployment point survives those details: sparse activation can reduce per-token expert compute without making the inactive expert weights disappear from memory.\n\nOn a memory-constrained device, resident weights are therefore a first-class constraint unless you are willing to stream/offload experts and pay the systems cost that introduces.\n\n## Shape decides kernels too\n\nDepth and vocabulary are not the only hidden variables.\n\nTwo configurations with similar parameter counts can behave differently because:\n\n- `d`, `d_ff`, or `d_h` align differently with kernel tile sizes,\n- a head configuration may or may not hit an optimized attention path,\n- quantization groups may fit one shape better than another,\n- the output projection may dominate one model but not another,\n- cache layout and batching strategy can change which operation is actually the bottleneck.\n\nThat leads to the most practical rule in the chapter:\n\n> **Use parameter count to design the search space. Use the target inference stack to choose the configuration.**\n\nA parameter equation is a planning tool, not a performance model.\n\n---\n\n## What to carry away\n\nThe story is one budget decision viewed through several ledgers.\n\n- **Write the parameter budget down.** For this decoder,\n  `P ≈ Vd + L[2d²(1+r) + 3d·d_ff]`. It immediately shows where capacity went.\n- **Write the state budget down separately.**\n  `KV bytes/token = 2L·n_kv·d_h·bytes`. MHA, GQA, and MQA can have the same hidden width and very different cache footprints.\n- **The tokenizer is an architectural decision.** A large `V` can consume a large fraction of a small model's weights, while a small `V` makes the same text longer in tokens.\n- **Do not collapse vocabulary trade-offs into one slogan.** A larger vocabulary can save KV/cache and sequence work while increasing the `d × V` output projection.\n- **A requested tokenizer vocabulary is not the same as a useful vocabulary.** In our toy trainer, the corpus stops supporting repeated merges before the requested size; another trainer could still force rarer merges.\n- **Equal parameters do not mean equal latency.** Depth adds serial stages; width changes the amount and shape of work inside each stage. Measure prefill and *real cached decode* separately — a single-token forward with no cache is neither.\n- **Active is not resident.** Sparse experts can reduce the active path while leaving a much larger set of weights that still has to live somewhere.\n- **Benchmark the exact shape on the exact serving stack.** Kernel alignment, quantization, cache layout, batching, and the output head are invisible to parameter count.\n\nIf one sentence survives, make it this:\n\n> **A parameter count tells you the size of the budget. The model you deploy is determined by how you spent it.**\n\n## Where this goes next\n\nEverything in this chapter is decided before training starts.\n\nThe next budget is data. At small scale, data mixture is not merely preprocessing: limited capacity forces capabilities to compete, so the distribution of training tokens decides what the model learns to spend that capacity on.\n\n## References\n\n- Liu et al., [*MobileLLM: Optimizing Sub-billion Parameter Language Models for On-Device Use Cases*](https://arxiv.org/abs/2402.14905), 2024 — deep-and-thin small-model design, embedding sharing, GQA, and the interaction between model shape and on-device inference.\n- Ainslie et al., [*GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints*](https://arxiv.org/abs/2305.13245), 2023 — grouped-query attention and the reduction in distinct K/V heads.\n- Sennrich, Haddow and Birch, [*Neural Machine Translation of Rare Words with Subword Units*](https://arxiv.org/abs/1508.07909), 2016 — BPE-style subword construction.\n- Shazeer, [*GLU Variants Improve Transformer*](https://arxiv.org/abs/2002.05202), 2020 — the three-matrix SwiGLU formulation and the `2/3` hidden-width adjustment used to match the parameter/computation budget of a conventional two-matrix FFN.\n\n",
    "supporting": [
      "s1-small-model-budget-5_files"
    ],
    "filters": [],
    "includes": {}
  }
}