{
  "hash": "65fbfa5a19bdc10a2b6bbc32b2dfb4c5",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Your Loss Spiked. Now What?\"\ndescription: \"A loss spike is not an event inside the loss curve. It is evidence left behind by a state transition the curve never showed you. Four links in the chain from loss to executed update, each looser than it looks — and a flight recorder that captures the transition instead of the symptom.\"\ncategories: [training, debugging, optimizers, autograd]\ndate: 2026-08-09\ndepth: \"Deep dive\"\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  freeze: auto\n---\n\nThe run had been fine for eleven hours. Then the loss goes from 2.1 to 2.9 in one step, comes most of the way back over the next fifty, and settles a little worse than it was. Nothing crashed. No NaN. The gradient norm you logged looks unremarkable.\n\nSo you stare at the curve. And the curve, it turns out, cannot answer the question, because it is a lossy view of something much bigger: a state transition involving your data, your autograd graph, your clipping, your optimizer's accumulated history, your gradient scaler, and your scheduler. The loss is one scalar summary of the *forward pass at one point in time*. It is not the thing that broke.\n\nThis post is about the five lines everybody writes and nobody reads:\n\n```python\noptimizer.zero_grad()\nloss = criterion(model(batch), target)\nloss.backward()\nclip_grad_norm_(model.parameters(), max_norm)\noptimizer.step()\n```\n\nFour of those five do something materially different from what most people assume. Not subtly different — differently enough that the debugging conclusions you draw from the loss curve can be wrong in a specific, reproducible way.\n\n> **TL;DR** — Loss, gradient, optimizer behaviour, and whether a step actually executes are four different signals, and every link between them is looser than it looks. A finite loss can produce a non-finite gradient. Global clipping couples layers that have nothing to do with each other. Adam's update can disagree with the gradient that produced it. And under AMP, `optimizer.step()` may quietly not run while the rest of the loop carries on. So the useful debugging object is not the loss curve — it's the transition immediately around the first bad observation, which means keeping it.\n\nEverything below runs on CPU in a few seconds. That is deliberate: these are not exotic large-scale phenomena, they are properties of the code you already have.\n\n::: {#ff234c3a .cell execution_count=1}\n``` {.python .cell-code}\nimport math\nimport torch\nimport torch.nn as nn\n\ntorch.set_num_threads(1)\nprint(\"torch\", torch.__version__)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntorch 2.8.0\n```\n:::\n:::\n\n\n---\n\n# Act I — What the loop actually does\n\n## The loop is not a straight line\n\nThe mental model this invites is five statements, executed in order, each doing what its name says. Gradients are zeroed. A loss is computed. Gradients are filled in. Large ones are trimmed. Parameters move.\n\nThe real object is a state machine with branches, and the branches are invisible from the call site. Gradients may be `None` rather than zero, and that changes which parameters the optimizer touches. The loss may be finite while the gradients are not. Clipping may report a number that no longer describes the gradients that exist after it returns. The optimizer's step depends on state accumulated over thousands of previous iterations. And under mixed precision, `step()` may decline to do anything at all.\n\n![The five statements read as a straight line. Underneath, each one has a branch the call site doesn't show — and the last splits into three separate events that most loops count as one. Read this as a map rather than as assumed background: every box in it is unpacked experimentally below.](07-fig1-loop-state-machine.png){#fig-state-machine}\n\nEach of the next four sections breaks one link in the chain. The pattern is the same every time: the assumption, the smallest demonstration that contradicts it, and what to do about it in production.\n\n## Loss is not gradient\n\n### The guard that never fires\n\nStart with the most common piece of hand-rolled safety code in the field — usually written just after being burned once:\n\n::: {#e360b9cb .cell execution_count=2}\n``` {.python .cell-code}\nloss = float(\"nan\")\n\nprint(f\"loss > 1000  -> {loss > 1000}\")\nprint(f\"loss < 1000  -> {loss < 1000}\")\nprint(f\"loss == loss -> {loss == loss}\")\nprint(f\"isfinite     -> {math.isfinite(loss)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nloss > 1000  -> False\nloss < 1000  -> False\nloss == loss -> False\nisfinite     -> False\n```\n:::\n:::\n\n\nEvery comparison involving `NaN` is False. Not just `>`, but `<` as well, and `==` against itself. So this guard:\n\n```python\nif loss > SPIKE_THRESHOLD:      # never true for NaN\n    skip_this_batch()\n```\n\nis inert for the exact condition most people wrote it to catch. It will happily catch a loss of 8000 and sail straight past a loss of `NaN`, forever. The code is syntactically correct, reads correctly, and does nothing.\n\nThe same is true of tensors — and this one bites harder, because the guard *looks* like it's using a proper tensor predicate:\n\n::: {#d02b1ee8 .cell execution_count=3}\n``` {.python .cell-code}\nt = torch.tensor(float(\"nan\"))\nprint(f\"(t > 1000).item()      -> {(t > 1000).item()}\")\nprint(f\"torch.isfinite(t)      -> {torch.isfinite(t).item()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(t > 1000).item()      -> False\ntorch.isfinite(t)      -> False\n```\n:::\n:::\n\n\n**Practical rule:** never write a NaN check as a magnitude comparison. Write `if not torch.isfinite(loss):` and nothing else. If you find yourself reaching for a threshold, you are testing for \"too big,\" which is a different and much less urgent problem.\n\n### A finite loss does not imply a finite gradient\n\nHere is the follow-up that catches people who *did* write the `isfinite` check correctly, and checked only the loss:\n\n::: {#a69d52c8 .cell execution_count=4}\n``` {.python .cell-code}\nx = torch.tensor(0.0, requires_grad=True)\nloss = torch.sqrt(x)                       # perfectly finite\nloss.backward()\n\nprint(f\"forward:  sqrt(0) = {loss.item()}\")\nprint(f\"backward: d/dx    = {x.grad.item()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nforward:  sqrt(0) = 0.0\nbackward: d/dx    = inf\n```\n:::\n:::\n\n\nThe forward value is 0.0. The derivative of `sqrt` at zero is infinite, and autograd reports it faithfully. Your loss guard passes, your gradients are already poisoned, and if that reaches a stateful optimizer unchecked it contaminates the moment buffers and everything computed from them — all without the loss ever looking wrong.\n\nThe family is the set of functions whose derivative blows up at a point where the function itself is perfectly finite: `sqrt(x)` and more generally $x^\\alpha$ for $0 < \\alpha < 1$ at the origin, and inverse trig at the edge of its domain — `acos(1)` returns 0.0 and differentiates to $-\\infty$, `asin(1)` returns $\\pi/2$ and differentiates to $+\\infty$.\n\nWorth distinguishing from a neighbouring family that people lump in with it: `log(0)` and division by zero produce non-finite values *in the forward pass*, so an `isfinite` check on the loss does catch them. It's the boundary-derivative cases that slip through, because there is genuinely nothing wrong with the number you checked.\n\nPyTorch gives you a hook for this that almost nobody sets:\n\n::: {#c464a783 .cell execution_count=5}\n``` {.python .cell-code}\nlin = nn.Linear(3, 3, bias=False)\nlin.weight.grad = torch.full_like(lin.weight, float(\"inf\"))\n\ntry:\n    torch.nn.utils.clip_grad_norm_(lin.parameters(), 1.0, error_if_nonfinite=True)\nexcept RuntimeError as e:\n    print(\"raised:\", str(e)[:70])\n\nprint(\"default for error_if_nonfinite is False — the check is opt-in\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nraised: The total norm of order 2.0 for gradients from `parameters` is non-fin\ndefault for error_if_nonfinite is False — the check is opt-in\n```\n:::\n:::\n\n\nAnd there is a sharp edge behind that default, which is worth seeing before you decide to leave it off:\n\n::: {#fc78dc34 .cell execution_count=6}\n``` {.python .cell-code}\np = torch.nn.Parameter(torch.tensor([1.0, 2.0]))\np.grad = torch.tensor([float(\"inf\"), 1.0])     # one component blew up\n\nnorm = torch.nn.utils.clip_grad_norm_([p], max_norm=1.0)   # default: no error\nprint(f\"returned norm : {norm.item()}\")\nprint(f\"gradients now : {p.grad.tolist()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nreturned norm : inf\ngradients now : [nan, 0.0]\n```\n:::\n:::\n\n\nThe clipping coefficient is `max_norm / (inf + 1e-6)`, which is exactly `0`. Multiplying through gives `inf * 0 = NaN` for the component that overflowed — and `1.0 * 0 = 0.0` for the component that was perfectly healthy. So the operation most people install *as a safety mechanism against exploding gradients* has, in the one case where a gradient truly exploded, converted a recoverable `inf` into an unrecoverable `NaN` and silently destroyed every other gradient in the model.\n\n**Gradient clipping is not a repair for non-finite gradients.** It assumes they are finite and merely large.\n\nAnd once you know gradients are non-finite, the next question is *whose*. This is the forensic move that follows:\n\n::: {#65af623d .cell execution_count=7}\n``` {.python .cell-code}\ndef nonfinite_grads(model):\n    \"\"\"Which parameters carry non-finite gradients? Development use only.\"\"\"\n    return [n for n, p in model.named_parameters()\n            if p.grad is not None and not torch.isfinite(p.grad).all()]\n\nprobe = nn.Sequential(nn.Linear(3, 3), nn.Linear(3, 3))\nfor p in probe.parameters():\n    p.grad = torch.zeros_like(p)\nprobe[1].bias.grad = torch.full_like(probe[1].bias, float(\"inf\"))\n\nprint(\"non-finite gradients in:\", nonfinite_grads(probe))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnon-finite gradients in: ['1.bias']\n```\n:::\n:::\n\n\nThat loop touches every parameter, so it is deliberately something you run *after* a cheap global check has already tripped — not on every step of a large model.\n\nNote what this rules out. Checking `torch.isfinite` on the value `clip_grad_norm_` hands back cannot help: by the time it returns, the mutation has already happened. The check has to sit *between* measuring and clipping, which means splitting the two operations that `clip_grad_norm_` fuses:\n\n::: {#b2c93ae0 .cell execution_count=8}\n``` {.python .cell-code}\ndef measure_then_clip(model, max_norm):\n    \"\"\"Measure first, decide, then mutate — never the other way round.\"\"\"\n    grads = [p.grad for p in model.parameters() if p.grad is not None]\n    total = torch.nn.utils.get_total_norm(grads)\n    if not torch.isfinite(total):\n        return total, None                       # caller records the reason and skips\n    torch.nn.utils.clip_grads_with_norm_(model.parameters(), max_norm, total)\n    return total, min(1.0, max_norm / (total.item() + 1e-6))\n\nprobe = nn.Linear(2, 2)\nfor p in probe.parameters():\n    p.grad = torch.full_like(p, float(\"inf\"))\ntotal, coef = measure_then_clip(probe, 1.0)\nprint(f\"non-finite path: norm={total.item()}  coef={coef}  \"\n      f\"grad still inf={probe.weight.grad.flatten()[0].item()}\")\n\nfor p in probe.parameters():\n    p.grad = torch.full_like(p, 10.0)\ntotal, coef = measure_then_clip(probe, 1.0)\nafter = torch.nn.utils.get_total_norm([p.grad for p in probe.parameters()])\nprint(f\"finite path    : norm={total.item():.3f}  coef={coef:.4f}  \"\n      f\"post-clip={after.item():.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnon-finite path: norm=inf  coef=None  grad still inf=inf\nfinite path    : norm=24.495  coef=0.0408  post-clip=1.0000\n```\n:::\n:::\n\n\nOn the non-finite path the gradients are left exactly as they were, so whatever logs the failure still has something to look at.\n\n**Practical rule:** in development, `error_if_nonfinite=True` is the simplest fail-fast option. If the loop needs to recover instead, measure with `get_total_norm`, check `isfinite`, and call `clip_grads_with_norm_` only when the norm is finite — recording *why* the step was skipped rather than skipping in silence.\n\n### The same loss, a hundred times the gradient\n\nNow the distinction that matters most for reading curves. Take the simplest model there is, one parameter, squared error:\n\n$$\\hat y = wx, \\qquad L = (\\hat y - y)^2, \\qquad \\frac{\\partial L}{\\partial w} = 2(\\hat y - y)\\,x$$\n\nThe loss depends only on the residual. The gradient depends on the residual **and on the input**. So two examples can have identical loss and wildly different gradients:\n\n::: {#acef73c9 .cell execution_count=9}\n``` {.python .cell-code}\nprint(f\"{'x':>8} {'y':>8} {'residual':>10} {'loss':>10} {'dL/dw':>12}\")\nfor x, y in [(1.0, 0.0), (10.0, 9.0), (100.0, 99.0)]:\n    w = torch.tensor(1.0, requires_grad=True)\n    L = (w * x - y) ** 2\n    L.backward()\n    print(f\"{x:>8.1f} {y:>8.1f} {(w.item()*x - y):>10.2f} \"\n          f\"{L.item():>10.4f} {w.grad.item():>12.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       x        y   residual       loss        dL/dw\n     1.0      0.0       1.00     1.0000         2.00\n    10.0      9.0       1.00     1.0000        20.00\n   100.0     99.0       1.00     1.0000       200.00\n```\n:::\n:::\n\n\nSame loss to four decimals in all three rows. Gradients spanning two orders of magnitude.\n\nThis is why a smooth loss curve is not reassurance. Loss measures *how wrong you are*. The gradient measures how wrong you are **multiplied by how sensitive the model is to the parameters at that input**. A batch of long sequences, or unusually large activations, or one sample with an extreme feature scale, can produce a gradient far outside the normal range while nudging the mean loss by almost nothing.\n\nOne clarification worth making, because it is stated wrongly all the time: with `reduction=\"mean\"` — the default for `CrossEntropyLoss` and `MSELoss` — the per-example *gradients* are averaged just like the losses are. There is no asymmetry in the averaging. The asymmetry is in what each quantity measures. A stable mean loss simply does not bound the gradient norm.\n\n**Practical rule, with the caveat that makes it honest.** A high percentile of the per-example loss, logged next to the mean, finds anomalous *samples*; `reduction=\"none\"` gives you that distribution, though not for free — a larger retained tensor, the cost of the quantile, and for token-level objectives a tensor of shape `batch × sequence`. Sample it or compute it on a cadence.\n\nBut per-example loss cannot detect the case just constructed, because all three rows have identical loss. Loss tails are not a proxy for gradient behaviour. Pair them with the pre-clip gradient norm, and go to per-layer contributions when that signal turns abnormal.\n\n## Gradient is not update\n\n### `clip_grad_norm_` reports the past\n\nA common training loop contains a line like this, and it is common to log the returned value as \"grad norm\":\n\n::: {#2dce11f8 .cell execution_count=10}\n``` {.python .cell-code}\nlin = nn.Linear(4, 4, bias=False)\nlin.weight.grad = torch.full_like(lin.weight, 10.0)\n\nbefore = lin.weight.grad.norm().item()\nreturned = torch.nn.utils.clip_grad_norm_(lin.parameters(), max_norm=1.0)\nafter = lin.weight.grad.norm().item()\n\nprint(f\"norm before the call : {before:.4f}\")\nprint(f\"value returned       : {returned.item():.4f}\")\nprint(f\"norm after the call  : {after:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnorm before the call : 40.0000\nvalue returned       : 40.0000\nnorm after the call  : 1.0000\n```\n:::\n:::\n\n\nThe function returns 40.0 while the gradients it just modified have norm 1.0. That is not a bug and it is not a bad design — the pre-clip norm is the diagnostically valuable number, and the post-clip norm is trivially `min(max_norm, pre)`. But the *temporal* mismatch surprises people: the value describes a state that no longer exists by the time you receive it.\n\nThe consequence is that a log line reading `grad_norm: 40.0` in a run with `max_norm=1.0` is not evidence that clipping failed. It is evidence that clipping did a lot of work. Which is information you want — but only if you also log the clipping coefficient, because 40.0 means something very different at `max_norm=1.0` than at `max_norm=100.0`:\n\n$$c = \\min\\left(1, \\frac{\\texttt{max\\_norm}}{\\texttt{total\\_norm} + 10^{-6}}\\right)$$\n\n::: {#2cc96888 .cell execution_count=11}\n``` {.python .cell-code}\ncoef = min(1.0, 1.0 / (before + 1e-6))\nprint(f\"clipping coefficient : {coef:.6f}\")\nprint(f\"post/pre ratio       : {after / before:.6f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nclipping coefficient : 0.025000\npost/pre ratio       : 0.025000\n```\n:::\n:::\n\n\n**Practical rule:** log the pre-clip norm *and* the coefficient. Logging the post-clip norm alone destroys the evidence — it is pinned to `max_norm` on exactly the steps you most need to understand.\n\n### One bad layer throttles every layer\n\nHere is the part of clipping that is genuinely counterintuitive. `clip_grad_norm_` computes **one** norm, treating every gradient as though concatenated into a single vector, then multiplies all of them by the same coefficient:\n\n::: {#1d3e3af7 .cell execution_count=12}\n``` {.python .cell-code}\nmodel = nn.Sequential(nn.Linear(4, 4, bias=False),\n                      nn.Linear(4, 4, bias=False),\n                      nn.Linear(4, 4, bias=False))\n\nfor i, p in enumerate(model.parameters()):\n    p.grad = torch.ones_like(p) * (0.05 if i < 2 else 100.0)  # layer 2 misbehaves\n\npre = [p.grad.norm().item() for p in model.parameters()]\ntotal = torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)\npost = [p.grad.norm().item() for p in model.parameters()]\n\nprint(f\"total norm across all layers: {total.item():.2f}\\n\")\nprint(f\"{'layer':>6} {'pre':>10} {'post':>10} {'factor':>10}\")\nfor i, (a, b) in enumerate(zip(pre, post)):\n    print(f\"{i:>6} {a:>10.3f} {b:>10.5f} {b/a:>10.5f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntotal norm across all layers: 400.00\n\n layer        pre       post     factor\n     0      0.200    0.00050    0.00250\n     1      0.200    0.00050    0.00250\n     2    400.000    1.00000    0.00250\n```\n:::\n:::\n\n\nRead the first two rows carefully. Layers 0 and 1 have norms of 0.2 — individually well under the `max_norm` of 1.0, so on their own they would not have been clipped at all. They get scaled by the same 0.0025 as the layer that actually caused the problem. Their updates for this step are effectively erased, and nothing they did caused it.\n\nSo global clipping is not *\"repair the exploding layer.\"* It is *\"shrink the entire proposed update direction until its total length fits.\"* Direction is preserved exactly; magnitude is cut for everyone. When one layer routinely dominates the norm — an embedding table early in training, an unnormalized head, a loss term with a large scale — the rest of the network is being silently starved on those steps.\n\n**Practical rule:** if you clip, log which parameter group contributed most of the norm, not just the total. A run where 90% of the norm comes from one module every step is a run where every other module's raw gradient is being scaled down without having done anything to deserve it. Under SGD that shrinks their updates directly. Under an adaptive optimizer it is less direct — as the next section shows — but it still propagates, through the optimizer state. Nothing in the loss curve will tell you either way.\n\n### On Adam's first step, gradient scale almost cancels\n\nNow the optimizer. Adam's update, ignoring weight decay and $\\epsilon$, is\n\n$$\\Delta\\theta = -\\eta \\cdot \\frac{\\hat m_t}{\\sqrt{\\hat v_t}}$$\n\nAt the very first step, with no history, $\\hat m = g$ and $\\hat v = g^2$, so the ratio is $g/|g| = \\operatorname{sign}(g)$. The magnitude cancels. Completely:\n\n::: {#cb9b7895 .cell execution_count=13}\n``` {.python .cell-code}\ndef adam_first_step(g, lr=1e-3):\n    p = torch.nn.Parameter(torch.tensor([0.0]))\n    opt = torch.optim.Adam([p], lr=lr)\n    p.grad = torch.tensor([g])\n    opt.step()\n    return p.item()\n\nfor g in [1e-3, 1.0, 1e3, 1e6]:\n    print(f\"gradient {g:>10.0e}  ->  Δθ = {adam_first_step(g):+.6e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ngradient      1e-03  ->  Δθ = -9.999899e-04\ngradient      1e+00  ->  Δθ = -9.999999e-04\ngradient      1e+03  ->  Δθ = -9.999999e-04\ngradient      1e+06  ->  Δθ = -9.999999e-04\n```\n:::\n:::\n\n\nA gradient of $10^{-3}$ and a gradient of $10^{6}$ — nine orders of magnitude apart — produce **nearly the same parameter displacement**. Not exactly the same: $\\epsilon$ in the denominator leaves the small-gradient case visibly short in the output above, which is itself a useful reminder that $\\epsilon$ is not decoration. But near enough that the scale has effectively been erased.\n\nBe precise about what that establishes. At fresh state, uniformly rescaling *one coordinate's* gradient largely cancels between the first- and second-moment terms of that coordinate's update. It does not follow that any 100× spike in the *global* gradient norm is harmless — a norm can grow because the direction changed, or because coordinates that were quiet became active, and neither of those cancels.\n\nWhat does follow is still worth carrying: current gradient magnitude need not translate proportionally into parameter displacement. And once optimizer history exists, even that simple cancellation stops being the whole story — the accumulated moments then govern both the magnitude and, as the next section shows, the direction.\n\nIt also means gradient clipping does something different under Adam than under SGD. Under plain SGD, with no momentum and no weight decay, clipping directly bounds the gradient-driven displacement. Under Adam it is not: it changes the gradient that *enters* the moment estimates, so its effect depends on the optimizer's existing state and reaches both the current update and every subsequent one through $m$ and $v$.\n\nA tempting next step is to conclude that Adam's update is therefore bounded near the learning rate, with a tidy ceiling of $(1-\\beta_1)/\\sqrt{1-\\beta_2} \\approx 3.16$. That figure circulates widely and it describes exactly one situation: a gradient arriving after negligible moment state. A shaped history beats it comfortably:\n\n::: {#4e8c1e8f .cell execution_count=14}\n``` {.python .cell-code}\ndef step_ratio(history, current, lr=1e-3):\n    p = torch.nn.Parameter(torch.tensor([0.0]))\n    opt = torch.optim.Adam([p], lr=lr)\n    for g in history:\n        p.grad = torch.tensor([g]); opt.step(); opt.zero_grad()\n    before = p.item()\n    p.grad = torch.tensor([current]); opt.step()\n    return abs(p.item() - before) / lr\n\nprint(f\"{'history':>34} {'|Δθ| / lr':>11}\")\nfor label, h in [(\"none (fresh)\", []),\n                 (\"500 zeros\", [0.0] * 500),\n                 (\"2000 zeros, then 10 x 1.0\", [0.0] * 2000 + [1.0] * 10),\n                 (\"5000 zeros, then 10 x 1.0\", [0.0] * 5000 + [1.0] * 10)]:\n    print(f\"{label:>34} {step_ratio(h, 1.0):>11.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                           history   |Δθ| / lr\n                      none (fresh)        1.00\n                         500 zeros        1.99\n         2000 zeros, then 10 x 1.0        6.10\n         5000 zeros, then 10 x 1.0        6.54\n```\n:::\n:::\n\n\nTwice the supposed ceiling, from nothing more exotic than a long quiet stretch followed by a burst. The durable statement is narrower: **at fresh state the gradient's magnitude cancels out of the update, and 3.16× is not a universal bound.** The step is a function of the entire gradient history, which is as much as this chapter needs from it.\n\n### The update can point the wrong way\n\nThis is the one that changes how you read a curve.\n\nAdam's numerator $\\hat m$ is an exponentially weighted average of past gradients. If that average has been pointing one way for a long time, a single opposing gradient does not immediately reverse it — the update keeps going the old way:\n\n::: {#3d1cb668 .cell execution_count=15}\n``` {.python .cell-code}\ndef adam_with_history(history, current, lr=1e-3, n=4):\n    p = torch.nn.Parameter(torch.zeros(n))\n    opt = torch.optim.Adam([p], lr=lr)\n    for g in history:\n        p.grad = torch.full((n,), g); opt.step(); opt.zero_grad()\n    before = p.detach().clone()\n    grad = torch.full((n,), current)\n    p.grad = grad.clone(); opt.step()\n    delta = p.detach() - before\n    cos = torch.dot(delta, -grad) / (delta.norm() * grad.norm())\n    return delta[0].item(), cos.item()\n\nprint(f\"{'history':>22} {'current g':>10} {'Δθ':>13} {'cos(Δθ, −g)':>13}\")\nfor label, h in [(\"fresh\", []), (\"30 x (+1.0)\", [1.0]*30), (\"30 x (−1.0)\", [-1.0]*30)]:\n    d, c = adam_with_history(h, +1.0)\n    print(f\"{label:>22} {'+1.0':>10} {d:>+13.3e} {c:>+13.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               history  current g            Δθ   cos(Δθ, −g)\n                 fresh       +1.0    -1.000e-03       +1.0000\n           30 x (+1.0)       +1.0    -1.000e-03       +1.0000\n           30 x (−1.0)       +1.0    +7.921e-04       -1.0000\n```\n:::\n:::\n\n\nRead the last row carefully. The current gradient is **positive**, so descent requires moving the parameter **down**. The parameter moves **up**. The cosine between the applied update and the descent direction is $-1$: the update is exactly anti-aligned with the gradient that produced it.\n\nNothing is broken. Adam is a filter over gradient history, and it is doing precisely what its update rule specifies. So for this coordinate on this step, the update is locally ascent-aligned with the current minibatch — and no quantity in the usual logging shows it. The loss is fine. The gradient norm is fine. The update magnitude is fine. Only the *alignment* is wrong, and alignment is rarely logged.\n\nThat is the metric this chapter is arguing for:\n\n$$\\cos(\\Delta\\theta,\\, -g_t) = \\frac{\\Delta\\theta \\cdot (-g_t)}{\\|\\Delta\\theta\\|\\,\\|g_t\\|}$$\n\nNear $+1$, the update agrees with the current batch's descent direction. Near $0$, it is mostly orthogonal — the optimizer is following history the current batch has no opinion about. Below $0$, the update opposes that batch's local descent direction, so to first order the batch's loss is predicted to rise. Whether it actually rises over a finite step also depends on curvature and step length, which is why the experiment below measures the loss directly instead of inferring it.\n\n### How often does that actually happen?\n\nA scalar toy is not evidence about real training, so let me measure it. A small MLP, a well-posed regression problem, Adam at a sane learning rate, no injected pathology — just ordinary minibatch training at four different batch sizes:\n\n::: {#e345a9fe .cell execution_count=16}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"The sweep: rate of anti-aligned updates vs batch size\"}\ntorch.manual_seed(0)\nW_true = torch.randn(8, 1)\n\ndef anti_alignment_rate(batch_size, steps=400, lr=3e-3, seed=0):\n    \"\"\"Fraction of steps whose executed update opposes that step's own gradient.\"\"\"\n    torch.manual_seed(seed)\n    model = nn.Sequential(nn.Linear(8, 32), nn.Tanh(), nn.Linear(32, 1))\n    opt = torch.optim.Adam(model.parameters(), lr=lr)\n    lossf = nn.MSELoss()\n    negative, worst = 0, (1.0, None, None)\n\n    for i in range(steps):\n        X = torch.randn(batch_size, 8); y = X @ W_true\n        opt.zero_grad()\n        loss_before = lossf(model(X), y)\n        loss_before.backward()\n        g = torch.cat([p.grad.flatten() for p in model.parameters()]).clone()\n        snapshot = [p.detach().clone() for p in model.parameters()]\n\n        opt.step()\n\n        delta = torch.cat([(p.detach() - s).flatten()\n                           for p, s in zip(model.parameters(), snapshot)])\n        cos = (torch.dot(delta, -g) / (delta.norm() * g.norm())).item()\n        loss_after = lossf(model(X), y).item()      # same batch, after the step\n        negative += cos < 0\n        if cos < worst[0]:\n            worst = (cos, loss_before.item(), loss_after)\n    return negative / steps, worst\n\nprint(f\"{'batch':>7} {'cos<0 across 4 seeds':>22} {'worst cos':>11} \"\n      f\"{'loss on that batch':>24}\")\nfor bs in [256, 32, 8, 2]:\n    results = [anti_alignment_rate(bs, seed=s) for s in range(4)]\n    rates = [r for r, _ in results]\n    cos, lb, la = min((w for _, w in results))          # most anti-aligned overall\n    print(f\"{bs:>7} {min(rates):>10.1%} – {max(rates):<9.1%} {cos:>11.3f}   \"\n          f\"{lb:>9.4f} -> {la:<9.4f} {'rose' if la > lb else 'fell'}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  batch   cos<0 across 4 seeds   worst cos       loss on that batch\n    256       0.0% – 0.8%           -0.092      0.2324 -> 0.2326    rose\n     32       2.0% – 3.5%           -0.235      0.1102 -> 0.1113    rose\n      8       7.2% – 10.8%          -0.588      0.0101 -> 0.0119    rose\n      2       7.0% – 13.8%          -0.481      0.0333 -> 0.0383    rose\n```\n:::\n:::\n\n\nTwo things fall out of this.\n\nFirst, it is not rare and it is not a bug. In this problem, anywhere from a fraction of a percent to more than a tenth of the updates are locally anti-aligned with the current batch's descent direction. And on the most anti-aligned transition of each run, re-evaluating that same batch after the step confirms that the finite update did in fact raise its loss — the first-order prediction holds where it was checked.\n\nSecond, **smaller batches consistently produce more anti-aligned updates here.** More gradient noise means the current gradient more often disagrees with the accumulated average, and momentum wins more often. The table shows seed ranges rather than single numbers, and they repay careful reading: the separation from 256 to 32 to 8 is clean, but the ranges for batch 8 and batch 2 overlap. Four seeds on a toy problem establish a direction, not a law, and any single-seed number here would have been misleading.\n\nBe careful what you conclude from that. Alignment also depends on the learning rate, the betas, the local curvature, the phase of training, and whether the data is stationary. A shift in the alignment distribution mid-run is therefore a clue worth chasing, not a diagnosis of batch noise specifically. And this is *one* mechanism by which a step can hurt — not an explanation for large late-training spikes, which remain a separate question.\n\n**Practical rule:** compute this periodically, not every step. It requires snapshotting parameters before the update, which at scale is expensive enough to change the thing you are measuring. A subset of layers, or a cadence you have actually timed on your own model, or capture triggered by a cheaper signal.\n\n![Three measured results, one per link in the chain. Left: identical losses, gradients two orders of magnitude apart. Centre: nine orders of magnitude of gradient collapsing onto a single step size. Right: the same gradient producing opposite directions, depending only on what came before.](07-fig2-loss-gradient-update.png){#fig-chain}\n\n## An attempted step is not an executed step\n\n### The scaler that silently declines\n\nUnder mixed precision, `GradScaler` multiplies the loss by a large factor so that small gradients survive fp16, then unscales before the step. If it finds `inf` or `NaN` in the gradients — which is expected and normal, it's how the scaler calibrates — it **skips `optimizer.step()` entirely** and reduces the scale for next time.\n\nThat is correct behavior. The problem is what the rest of the loop does in the meantime:\n\n::: {#387044cb .cell execution_count=17}\n``` {.python .cell-code}\ntorch.manual_seed(0)\nmodel = nn.Linear(2, 1)\nopt = torch.optim.SGD(model.parameters(), lr=0.1)\nsched = torch.optim.lr_scheduler.StepLR(opt, step_size=1, gamma=0.9)\nscaler = torch.amp.GradScaler(device=\"cpu\")\n\nattempted = moved_n = 0\nprint(f\"{'step':>5} {'moved':>9} {'scale':>9} {'lr':>9}\")\nfor step in range(5):\n    opt.zero_grad()\n    loss = model(torch.randn(4, 2)).sum()\n    scaler.scale(loss).backward()\n\n    if step == 2:                                   # stand in for an fp16 overflow\n        for p in model.parameters():\n            p.grad = p.grad * float(\"inf\")\n\n    snapshot = [p.detach().clone() for p in model.parameters()]\n    scaler.step(opt)\n    scaler.update()\n    sched.step()                                    # unconditional — this is the bug\n\n    attempted += 1\n    moved = any(not torch.equal(a, b.detach())\n                for a, b in zip(snapshot, model.parameters()))\n    moved_n += moved\n    print(f\"{step:>5} {str(moved):>9} {scaler.get_scale():>9.0f} \"\n          f\"{opt.param_groups[0]['lr']:>9.5f}\")\n\nprint(f\"\\nattempted {attempted}, parameters moved {moved_n}, \"\n      f\"scheduler advanced {attempted} -> drift {attempted - moved_n}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n step     moved     scale        lr\n    0      True     65536   0.09000\n    1      True     65536   0.08100\n    2     False     32768   0.07290\n    3      True     32768   0.06561\n    4      True     32768   0.05905\n\nattempted 5, parameters moved 4, scheduler advanced 5 -> drift 1\n```\n:::\n:::\n\n\nStep 2 did not happen. The parameters are bit-identical before and after. The scale halved from 65536 to 32768, which is the scaler correctly recalibrating. And the scheduler advanced anyway, because nothing told it not to.\n\nOne skipped step is nothing. But skips can cluster early, while the scaler is still searching for a workable level — which is exactly where step-wise warmup lives. Your \"step 500\" is then not 500 updates, and your warmup finished before the optimizer had done the work it was warming up for.\n\nWorth scoping: this only matters for schedules defined in *optimizer-update* units — step-wise warmup, cosine or linear decay counted in steps, OneCycle. An epoch-based scheduler runs on a different clock and doesn't care, and a metric-driven one like `ReduceLROnPlateau` runs on a third. The bug is not \"the scheduler advanced\"; it is \"the scheduler advanced in units of attempted steps while claiming to count updates.\"\n\n> **Honesty note on this demonstration.** `torch.autocast(\"cpu\")` uses bfloat16, whose exponent range matches fp32, so loss scaling is typically unnecessary there for range protection. The `inf` above is injected by hand. What these cells demonstrate is `GradScaler`'s *control flow* — faithfully, on any machine — not the frequency with which overflow occurs in a real fp16 run. Note also that the injection has to happen *before* `unscale_`, because that is where the scaler inspects the gradients; inject afterwards and the check has already passed, the step executes, and you have corrupted the model rather than demonstrated a skip. Real overflow frequency is a property of your model, your loss scale and your hardware — not of this cell.\n\n### Detecting whether the step happened\n\nSo how does the loop find out? Not from the return value — `scaler.step()` returns the optimizer's return value, and the common optimizers return `None` from `step()` whether it ran or not — the API permits a closure-derived value, so the return is not a reliable executed-step signal either way. Comparing parameters before and after works but costs a full copy of the model every iteration.\n\nThe clean answer is an optimizer post-step hook, which fires only when `step()` actually executes:\n\n::: {#dd274d54 .cell execution_count=18}\n``` {.python .cell-code}\ntorch.manual_seed(0)\nmodel = nn.Linear(2, 1)\nopt = torch.optim.SGD(model.parameters(), lr=0.1)\nsched = torch.optim.lr_scheduler.StepLR(opt, step_size=1, gamma=0.9)\nscaler = torch.amp.GradScaler(device=\"cpu\")\n\nexecuted_steps = 0\ndef _count(optimizer, args, kwargs):\n    global executed_steps\n    executed_steps += 1\n\nhandle = opt.register_step_post_hook(_count)\n\nprint(f\"{'step':>5} {'hook fired':>12} {'executed total':>16} {'lr':>9}\")\nfor step in range(5):\n    opt.zero_grad()\n    scaler.scale(model(torch.randn(4, 2)).sum()).backward()\n    if step == 2:\n        for p in model.parameters():\n            p.grad = p.grad * float(\"inf\")\n\n    before = executed_steps\n    scaler.step(opt)\n    scaler.update()\n\n    if executed_steps > before:       # only advance the schedule on a real step\n        sched.step()\n\n    print(f\"{step:>5} {str(executed_steps > before):>12} {executed_steps:>16} \"\n          f\"{opt.param_groups[0]['lr']:>9.5f}\")\n\nhandle.remove()\nprint(\"\\nno drift: the scheduler advanced exactly as often as step() executed\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n step   hook fired   executed total        lr\n    0         True                1   0.09000\n    1         True                2   0.08100\n    2        False                2   0.08100\n    3         True                3   0.07290\n    4         True                4   0.06561\n\nno drift: the scheduler advanced exactly as often as step() executed\n```\n:::\n:::\n\n\nThe hook does not fire on step 2, the scheduler holds, and the learning rate now tracks executed steps rather than loop iterations.\n\nThat is a lightweight, public-API way to count executed optimizer steps. Twelve lines, no dependencies, and it turns \"attempted vs executed\" from a concept into a counter you can put on a dashboard.\n\nOne precision worth keeping, because it is easy to over-read the hook: it tells you `step()` **executed**, not that any parameter changed. Those are different:\n\n::: {#e7a41bf4 .cell execution_count=19}\n``` {.python .cell-code}\nlin = nn.Linear(2, 2)\nopt = torch.optim.SGD(lin.parameters(), lr=0.1)\nfired = []\nh = opt.register_step_post_hook(lambda o, a, k: fired.append(1))\n\nfor label, setup in [(\"all grads None\", \"none\"), (\"lr = 0.0\", \"zero_lr\")]:\n    if setup == \"none\":\n        opt.zero_grad(set_to_none=True)\n    else:\n        for q in lin.parameters():\n            q.grad = torch.ones_like(q)\n        opt.param_groups[0][\"lr\"] = 0.0\n\n    before_n, snap = len(fired), [q.detach().clone() for q in lin.parameters()]\n    opt.step()\n    moved = any(not torch.equal(a, b.detach()) for a, b in zip(snap, lin.parameters()))\n    print(f\"{label:>16}: hook fired={len(fired) > before_n}   parameters moved={moved}\")\nh.remove()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  all grads None: hook fired=True   parameters moved=False\n        lr = 0.0: hook fired=True   parameters moved=False\n```\n:::\n:::\n\n\nSo the chain has three links, not two: **attempted step → executed step → non-zero parameter change.** The hook is a cheap answer to the middle one. The last one costs a parameter snapshot, which is why the recorder in Act II only asks it occasionally.\n\n**Practical notes.** Register one counter per optimizer — `GradScaler` decides independently for each, so with a separate optimizer for, say, a discriminator, one can be skipped while the other steps. And if you clip or inspect gradients under AMP, you must call `scaler.unscale_(optimizer)` first, or you will be clipping numbers that are still multiplied by 65536 and your `max_norm` will mean nothing:\n\n```python\nscaler.scale(loss).backward()\nscaler.unscale_(optimizer)                     # gradients now in real units\npre_clip = clip_grad_norm_(model.parameters(), max_norm)\nscaler.step(optimizer)                         # knows it was already unscaled\nscaler.update()\n```\n\n### `grad is None` is not `grad == 0`\n\nOne more, and it is the shortest of the lot. The default changed to `set_to_none=True` some releases ago, and it has semantics:\n\n::: {#ea7ce83c .cell execution_count=20}\n``` {.python .cell-code}\nimport inspect\ndefault = inspect.signature(torch.optim.Optimizer.zero_grad).parameters[\"set_to_none\"].default\nprint(f\"zero_grad default: set_to_none={default}\\n\")\n\nprint(f\"{'set_to_none':>12} {'bias.grad':>12} {'bias moved by':>15}\")\nfor stn in (True, False):\n    lin = nn.Linear(2, 2)\n    opt = torch.optim.SGD(lin.parameters(), lr=0.1, momentum=0.9, weight_decay=0.5)\n\n    lin.weight.grad = torch.ones_like(lin.weight)      # both used once\n    lin.bias.grad = torch.ones_like(lin.bias)\n    opt.step()\n    opt.zero_grad(set_to_none=stn)\n\n    b0 = lin.bias.detach().clone()\n    lin.weight.grad = torch.ones_like(lin.weight)      # bias NOT used this step\n    opt.step()\n\n    state = \"None\" if lin.bias.grad is None else \"zeros\"\n    print(f\"{str(stn):>12} {state:>12} \"\n          f\"{(b0 - lin.bias.detach()).abs().max().item():>15.5f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nzero_grad default: set_to_none=True\n\n set_to_none    bias.grad   bias moved by\n        True         None         0.00000\n       False        zeros         0.14653\n```\n:::\n:::\n\n\nA parameter whose `.grad` is `None` is **skipped** by the optimizer. A parameter whose `.grad` is a tensor of zeros is **processed**: existing momentum still carries it, and SGD's weight-decay term still acts on it. Zero gradient does not mean zero update. (Note that SGD's `weight_decay` is the conventional L2 term folded into the gradient — `AdamW`'s decoupled decay is a different mechanism, and it moves a zero-gradient parameter too.)\n\n| after backward | optimizer behaviour |\n|---|---|\n| `p.grad is None` | parameter skipped entirely |\n| `p.grad` is all zeros | processed; momentum and weight decay may still move it |\n\n: {tbl-colwidths=\"[35,65]\"}\n\nThe exact displacement depends on your optimizer, learning rate, momentum state and decay, so don't memorize the number above — memorize the distinction. It matters wherever parameters are conditionally used: mixture-of-experts routing, multi-task heads where one task is absent from a batch, frozen-then-unfrozen modules, and any branch that some batches don't take. Switching `set_to_none` changes whether those parameters drift on the steps they weren't used.\n\n## The first bad loss points backwards\n\nNow put the timeline together, because this is what makes the whole chapter actionable:\n\n```\n                    batch B_t\n                        ↓\n  parameters θ_t  →  loss L_t  →  gradient g_t     ← L_t is what you logged\n         ↑                             ↓\n  previous transition          clip, optimizer, scaler\n                                       ↓\n                                parameters θ_{t+1}\n```\n\nThe loss you logged at step $t$ was computed with $\\theta_t$, *before* that step's update ran. So a bad $L_t$ **cannot have been caused by the optimizer step that follows it.** That single fact eliminates the thing most people look at first.\n\nWhat it leaves is $L_t = F(\\theta_t,\\, B_t,\\, s_t,\\, \\xi_t)$ — parameters, batch, and two things people forget: $s_t$, the mutable state carried in the model (normalization running statistics, any custom module that accumulates), and $\\xi_t$, the stochastic state (dropout masks, augmentation, dataloader shuffling). The first two suspects are the state entering the forward and the batch being evaluated; the other two are why a \"reproduce it\" attempt sometimes doesn't.\n\nThat fork is the whole diagnosis. When you see a spike at step 12,047, there are two objects worth having: the transition from 12,046 into 12,047 — pre-clip norm, whether the step executed, alignment, learning rate, whether a checkpoint had just been resumed — and the identity of batch 12,047, so you can feed it again and see whether the loss is high on it for any set of weights. On which: a batch ID makes replay *possible*, not automatic. A faithful replay also needs the parameters from that step, the model's mutable buffers, and the RNG state — which is a good argument for the checkpoint discussion at the end of this chapter, and a good reason to record the seed alongside the batch ID.\n\n![The spike at 12 047 was computed before that step's update ran, so the update cannot be the cause. What can be: the transition that produced those parameters, and the batch that was fed to them. Both are gone by the time you look, unless something kept them.](07-fig3-forensic-timeline.png){#fig-forensics}\n\nAnd there is the practical problem: by the time you notice, that transition is gone. You logged a scalar.\n\n---\n\n# Act II — Capture the transition, not the symptom\n\n## A flight recorder, not a dashboard\n\nA dashboard shows you the present. A spike is evidence about the recent past. So the right instrument is a small ring buffer that keeps the last few dozen transitions and persists itself when something trips.\n\nThe design constraint that matters is cost. Some of these fields are free because you're already computing them; others require extra work per step. Separate them:\n\n**Cheap, always on** — raw unsmoothed loss, a finite flag, learning rate, AMP scale, attempted and executed counters, batch identifiers, and the pre-clip norm and clipping coefficient *if you were clipping anyway*.\n\n**Periodic or anomaly-triggered** — per-example loss percentiles, per-layer norm contributions, update-to-weight ratio, and the update–gradient cosine. These need parameter snapshots or extra reductions. Compute them on a cadence or behind an anomaly trigger, and pick that cadence only after measuring its overhead on your own model.\n\n::: {#24d4a5c6 .cell execution_count=21}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"FlightRecorder — ring buffer with cheap and expensive tiers\"}\nfrom collections import deque\n\nclass FlightRecorder:\n    \"\"\"Ring buffer of recent training transitions, dumped when something trips.\n\n    Cheap fields are recorded every step. Expensive ones (those needing a\n    parameter snapshot) are recorded on an interval.\n    \"\"\"\n\n    def __init__(self, capacity=32, deep_every=10):\n        self.buf = deque(maxlen=capacity)\n        self.deep_every = deep_every\n        self.attempted = 0\n        self.executed = 0\n        self.sched_n = 0\n\n    def snapshot(self, model):\n        \"\"\"Call before optimizer.step() on deep steps; returns None otherwise.\"\"\"\n        if self.attempted % self.deep_every:\n            return None\n        return [p.detach().clone() for p in model.parameters()]\n\n    def record(self, *, step, loss, model, snapshot=None, grad=None,\n               pre_clip=None, clip_coef=None, lr=None, scale=None,\n               executed=None, scheduled=False, batch_id=None):\n        self.attempted += 1\n        if executed:\n            self.executed += 1\n        if scheduled:\n            self.sched_n += 1\n\n        row = dict(step=step,\n                   loss=float(loss),\n                   finite=bool(torch.isfinite(torch.as_tensor(loss))),\n                   pre_clip=pre_clip, clip_coef=clip_coef,\n                   lr=lr, scale=scale, executed=executed,\n                   attempted_n=self.attempted, executed_n=self.executed,\n                   sched_n=self.sched_n,\n                   batch_id=batch_id, ratio=None, cos=None)\n\n        if snapshot is not None:                       # the expensive half\n            delta = torch.cat([(p.detach() - s).flatten()\n                               for p, s in zip(model.parameters(), snapshot)])\n            before = torch.cat([s.flatten() for s in snapshot])   # pre-update norm\n            row[\"ratio\"] = (delta.norm() / (before.norm() + 1e-12)).item()\n            if grad is not None and delta.norm() > 0:\n                row[\"cos\"] = (torch.dot(delta, -grad) /\n                              (delta.norm() * grad.norm() + 1e-12)).item()\n        self.buf.append(row)\n\n    @staticmethod\n    def clip_coefficient(total_norm, max_norm):\n        \"\"\"None when the norm is non-finite — min(1, nan) silently returns 1.\"\"\"\n        if not math.isfinite(total_norm):\n            return None\n        return min(1.0, max_norm / (total_norm + 1e-6))\n\n    def dump(self, n=6, clocks=False):\n        cols = f\"{'step':>5} {'loss':>9} {'fin':>4} {'preclip':>9} {'coef':>7}\"\n        cols += (f\" {'lr':>8} {'scale':>8} {'att/exe/sch':>13}\" if clocks\n                 else f\" {'exe':>4}\")\n        print(cols + f\" {'ratio':>9} {'cos':>7}\")\n        for r in list(self.buf)[-n:]:\n            f = lambda v, sp: (sp.format(v) if v is not None else \"  -\")\n            line = (f\"{r['step']:>5} {r['loss']:>9.4f} {str(r['finite'])[0]:>4} \"\n                    f\"{f(r['pre_clip'], '{:>9.3f}'):>9} \"\n                    f\"{f(r['clip_coef'], '{:>7.4f}'):>7}\")\n            if clocks:\n                line += (f\" {f(r['lr'], '{:>8.5f}'):>8} {f(r['scale'], '{:>8.0f}'):>8}\"\n                         f\" {r['attempted_n']:>3}/{r['executed_n']:>3}/{r['sched_n']:<3}\")\n            else:\n                line += f\" {str(r['executed'])[0]:>4}\"\n            print(line + f\" {f(r['ratio'], '{:>9.2e}'):>9} \"\n                         f\"{f(r['cos'], '{:>+7.3f}'):>7}\")\n```\n:::\n\n\nTwo design decisions worth calling out. The loss stored is **raw**, never the smoothed value you plot — smoothing is a display choice and it destroys exactly the single-step evidence you need. And `batch_id` is not decoration: if the recorder tells you the transition into step 12,047 was anomalous, the very next thing you want is to re-run that batch, and you can only do that if you know which one it was.\n\n**And a scoping warning, because this is teaching code.** `[p.detach().clone() for p in model.parameters()]` is fine for a model of this size and completely inappropriate for a large one — at billions of parameters it is not merely \"not free,\" it may not fit, and the memory pressure alone can change what you were trying to measure. In a real system: snapshot a fixed subset of layers, or accumulate the statistics inside an optimizer hook where the deltas are already available, or capture deeply only after a cheap always-on signal has already tripped. Pick the cadence by measuring its overhead on your own model, not by copying a number out of a blog post.\n\n## Replay A: the update that disagreed with its own gradient\n\nNow use it. A normal run, small batches, deliberately noisy — and we go looking for the most anti-aligned transition it produced:\n\n::: {#269c2710 .cell execution_count=22}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Replay A — train with small batches until the recorder trips\"}\ntorch.manual_seed(3)\nmodel = nn.Sequential(nn.Linear(8, 32), nn.Tanh(), nn.Linear(32, 1))\nopt = torch.optim.Adam(model.parameters(), lr=3e-3)\nlossf = nn.MSELoss()\nrec = FlightRecorder(capacity=64, deep_every=1)\n\nTRIP = -0.30                                   # dump the buffer when alignment goes bad\n\nfor step in range(400):\n    X = torch.randn(4, 8); y = X @ W_true\n    opt.zero_grad()\n    loss = lossf(model(X), y)\n    loss.backward()\n\n    g = torch.cat([p.grad.flatten() for p in model.parameters()]).clone()\n    pre_clip = torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n    snap = rec.snapshot(model)\n    opt.step()\n\n    rec.record(step=step, loss=loss.item(), model=model, snapshot=snap, grad=g,\n               pre_clip=pre_clip.item(),\n               clip_coef=rec.clip_coefficient(pre_clip.item(), 1.0),\n               lr=opt.param_groups[0][\"lr\"], executed=True, batch_id=step)\n\n    cos = rec.buf[-1][\"cos\"]\n    if cos is not None and cos < TRIP:\n        after = lossf(model(X), y).item()          # same batch, after the step\n        print(f\"tripped at step {step}: cos = {cos:+.3f}\")\n        print(f\"loss on batch {step}: {loss.item():.5f} -> {after:.5f} \"\n              f\"({'rose' if after > loss.item() else 'fell'})\\n\")\n        rec.dump(5)\n        break\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntripped at step 123: cos = -0.382\nloss on batch 123: 0.28032 -> 0.29854 (rose)\n\n step      loss  fin   preclip    coef  exe     ratio     cos\n  119    0.3402    T     3.836  0.2607    T  6.43e-03  +0.631\n  120    0.0300    T     0.712  1.0000    T  6.32e-03  +0.521\n  121    0.2044    T     1.997  0.5008    T  5.57e-03  +0.210\n  122    0.0984    T     1.411  0.7087    T  4.52e-03  -0.258\n  123    0.2803    T     2.937  0.3404    T  3.41e-03  -0.382\n```\n:::\n:::\n\n\nNothing here is broken. There is no injected pathology and no adversarial construction — just Adam, small batches, and momentum. The recorder tripped on its own, and the loss on that batch went up after the step that batch paid for.\n\nNow read the `cos` column upward from the trip. It does not jump; it *slides* — positive and healthy, then weakening, then through zero, then negative for two consecutive steps. The optimizer was progressively disagreeing with the incoming batches for several steps before the trip fired.\n\nAnd look at what the other columns were doing meanwhile. The pre-clip norm on the tripped step sits squarely inside the range of its neighbours. The update ratio is, if anything, *smaller* than the preceding steps. Neither column flags anything. If pre-clip norm and update magnitude were your only two signals — and for most training loops they are — this transition is completely invisible. **The alignment column is the only one carrying the information.** That is the whole argument for paying to compute it.\n\n## Replay B: the clocks come apart\n\nThe second replay is the AMP failure with the recorder attached, so you can see what it looks like in the log rather than in a narrative:\n\n::: {#35d2d13d .cell execution_count=23}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Replay B — AMP skips, naive scheduler, recorder attached\"}\ntorch.manual_seed(0)\nmodel = nn.Linear(4, 1)\nopt = torch.optim.SGD(model.parameters(), lr=0.05, momentum=0.9)\nsched = torch.optim.lr_scheduler.StepLR(opt, step_size=1, gamma=0.95)\nscaler = torch.amp.GradScaler(device=\"cpu\")\nrec = FlightRecorder(capacity=16, deep_every=1)\n\nexecuted_flag = {\"v\": False}\nh = opt.register_step_post_hook(lambda o, a, k: executed_flag.__setitem__(\"v\", True))\n\nfor step in range(6):\n    X = torch.randn(16, 4); y = X.sum(1, keepdim=True)\n    opt.zero_grad()\n    loss = nn.functional.mse_loss(model(X), y)\n    scaler.scale(loss).backward()\n\n    if step in (2, 3):                                # stand-in for fp16 overflow,\n        for p in model.parameters():                  # injected while still scaled\n            p.grad = p.grad * float(\"inf\")\n\n    lr_used = opt.param_groups[0][\"lr\"]               # the LR THIS step runs under\n    scale_used = scaler.get_scale()                   # ...and the scale it runs under\n    scaler.unscale_(opt)                              # this is where the scaler looks\n    g = torch.cat([p.grad.flatten() for p in model.parameters()]).clone()\n\n    # measure first, mutate only if the measurement is usable\n    grads = [p.grad for p in model.parameters() if p.grad is not None]\n    pre_clip = torch.nn.utils.get_total_norm(grads)\n    if torch.isfinite(pre_clip):\n        torch.nn.utils.clip_grads_with_norm_(model.parameters(), 1.0, pre_clip)\n        coef = min(1.0, 1.0 / (pre_clip.item() + 1e-6))\n    else:\n        coef = None                                   # do NOT clip inf into NaN\n    snap = rec.snapshot(model)\n\n    executed_flag[\"v\"] = False\n    scaler.step(opt)\n    scaler.update()\n    sched.step()                                      # NAIVE: advances regardless\n\n    rec.record(step=step, loss=loss.item(), model=model, snapshot=snap, grad=g,\n               pre_clip=pre_clip.item(), clip_coef=coef,\n               lr=lr_used, scale=scale_used,        # not the post-sched.step() value\n               executed=executed_flag[\"v\"], scheduled=True, batch_id=step)\n\nh.remove()\nrec.dump(6, clocks=True)\nprint(f\"\\nattempted {rec.attempted} / executed {rec.executed} / \"\n      f\"scheduled {rec.sched_n}   -> drift {rec.sched_n - rec.executed}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n step      loss  fin   preclip    coef       lr    scale   att/exe/sch     ratio     cos\n    0    3.1823    T     2.835  0.3527  0.05000    65536   1/  1/1    7.77e-02  +1.000\n    1    7.9891    T     7.555  0.1324  0.04750    65536   2/  2/2    1.43e-01  +0.983\n    2    4.1737    T       inf       -  0.04512    65536   3/  2/3    0.00e+00       -\n    3    4.1906    T       inf       -  0.04287    32768   4/  2/4    0.00e+00       -\n    4    5.7833    T     6.435  0.1554  0.04073    16384   5/  3/5    1.68e-01  +0.842\n    5    5.6942    T     5.708  0.1752  0.03869    16384   6/  4/6    2.19e-01  +0.965\n\nattempted 6 / executed 4 / scheduled 6   -> drift 2\n```\n:::\n:::\n\n\nThis loop advances the scheduler unconditionally — the way almost every training script does — and the `att/exe/sch` column is the whole diagnosis. Three counters that should march together, visibly coming apart at step 2 and never re-converging. The pre-clip norm is non-finite on exactly those steps, the clipping coefficient correctly declines to report a number rather than printing a misleading `1.0`, the update ratio is zero because the parameters genuinely did not move, and the learning rate kept decaying through all of it.\n\nNotice also what *didn't* happen: the loss stays finite throughout. The scaler did its job — it saw non-finite gradients, declined to apply them, and the model survived. This is the part people misread most often. **The skipped steps are not the failure; they are the mechanism working.** The failure is the schedule advancing as though they hadn't been skipped, and the only reason it is visible here is that we counted the two clocks separately.\n\nThe fix is the hook from Act I — wrap `sched.step()` in `if executed_flag[\"v\"]:` and the third counter tracks the second. One line, once you know which line.\n\nTwo things in that loop are deliberate, and both come from earlier sections.\n\n`torch.nn.utils.get_total_norm` measures without touching anything; `clip_grads_with_norm_` does the mutation. Splitting them lets the loop check `isfinite` on the norm *before* deciding to clip — because `clip_grad_norm_`, which does both at once, would have turned those `inf` gradients into `NaN` and zeroed every healthy gradient alongside them. The step was going to be skipped anyway, so nothing would have broken; but a recorder that corrupts the evidence it is recording is not a recorder. This is the production shape of the safety rule from Act I.\n\nA third detail is easy to get wrong and quietly ruins the log. The learning rate is captured *before* `sched.step()` runs. Read it afterwards and you record the rate for the *next* transition, not the one you are describing — in a chapter arguing that telemetry exists to reconstruct the transition that happened, logging the wrong side of the scheduler would be a small disaster.\n\nThe other is the ordering, which is load-bearing: `unscale_` comes before `clip_grad_norm_`, which comes before `scaler.step()`. Get that wrong and the pre-clip norm you record is too large by whatever the loss scale happens to be at that moment — a moving target, since the scaler adapts it — so your clipping threshold is meaningless, and the log you were relying on to debug the run is itself wrong.\n\n## Triage, once you have the transition\n\nWith those signals in the recorder, the diagnosis becomes a lookup rather than a guess:\n\n| observation | first place to look |\n|---|---|\n| Loss non-finite | inputs and forward activations; arithmetic that overflows in the *forward* — `log(0)`, division by zero, `sqrt` of a negative |\n| Loss finite, gradients non-finite | a boundary derivative where the forward was fine — `sqrt(0)`, `acos(1)`; also AMP overflow and custom backward functions |\n| Large pre-clip norm, tiny clip coefficient | which parameter group contributed the norm; an anomalous batch |\n| Ordinary gradient, abnormal update ratio or cosine | optimizer state, learning-rate change, a checkpoint resume |\n| No optimizer attempt this microstep | gradient-accumulation boundary, or intentional gating |\n| Attempted, but `step()` never executed | AMP skipping on non-finite gradients |\n| `step()` executed, but nothing moved | `grad is None` for that parameter, zero LR, or an update that rounded away |\n| Loss spike with no abnormal transition | a data outlier, a distribution boundary, or logging misalignment |\n\nThen, whichever row you land on: **inspect the transition before the first bad observation, not the transition it appeared in.**\n\nThe last row deserves its own note, because it is the one most often skipped. If the transition genuinely looks normal, believe the instrument: a clean parameter transition shifts suspicion toward the current batch, the stochastic state, the mutable buffers, or a mismatch between what was logged and what was assumed. None of those is fixed by tuning the learning rate.\n\n## What one process cannot show you\n\nEverything above is single-process and CPU, and it stays honest by construction. Distributed training adds failure modes that none of these cells can reproduce, and here I am reporting operational experience rather than measurement — treat it accordingly.\n\nThe one thing that is documented rather than anecdotal: with a sharded model under FSDP, `torch.nn.utils.clip_grad_norm_` is not the right call, because each rank holds only a shard of each gradient and the true norm spans all of them. FSDP provides its own `clip_grad_norm_`, and it must be called on every rank, because it performs a collective.\n\nThe rest is what tends to bite:\n\n- **Be explicit about where a diagnostic is measured.** Under ordinary DDP, gradients are averaged during backward, so a gradient norm computed afterwards is already a distributed quantity — it cannot show you the rank-local gradient that produced it. If rank-local anomalies matter, capture per-rank loss and input statistics *before* the reduction. The same applies to the loss you log: one rank's, or an average, and a rank receiving corrupted data can move an average by very little.\n- **Non-standard topologies need an explicit failure policy.** With `no_sync`, sharded, pipeline or model-parallel setups, ranks can end up making independent decisions about whether to skip a step. Decide deliberately whether skip decisions are collective; don't let it be an accident of where the check happens to sit.\n- **Resume restores less than you think.** Model weights are the easy part. Optimizer moments, scheduler position, scaler scale, RNG state, sampler position and accumulation phase all have to come back too, or the run you resumed is not the run you stopped. A spike immediately after a resume is a different diagnosis from a spike mid-run, and the first thing to check is which of those pieces was actually in the checkpoint.\n\n## What to carry away\n\n- **A NaN guard written as a magnitude comparison never fires.** Every comparison with `NaN` is False, including `<`. Use `torch.isfinite` and nothing else.\n- **A finite loss does not imply finite gradients.** `sqrt(0)` is finite going forward and infinite coming back. `error_if_nonfinite=True` exists and is off by default.\n- **The same loss can carry very different gradients**, because the gradient also contains the model's sensitivity to the input. Loss tails find anomalous samples but are not gradient telemetry — pair them with the pre-clip gradient norm.\n- **`clip_grad_norm_` returns the pre-clip norm**, after having already modified the gradients. Log it together with the clipping coefficient; the post-clip norm alone tells you nothing. And it is not a repair for non-finite gradients — it turns an `inf` into a `NaN` and zeros every other gradient in the model.\n- **Global clipping couples every parameter it touches.** One dominant layer scales everyone else down by the same factor. Log which group contributed the norm.\n- **At fresh state, Adam's update is nearly independent of gradient magnitude** — nine orders of magnitude of gradient, one step size. And the often-quoted 3.16× lr figure is not a universal bound on the step: optimizer history matters, and a shaped history reaches 6.54× here.\n- **The executed update can oppose the current gradient.** In the toy MLP above it occurs on a nontrivial fraction of steps, more at smaller batch sizes, and norm-based telemetry cannot see it — pre-clip norm and update magnitude both look ordinary, because the mismatch is one of direction.\n- **Attempted, executed, and moved are three different things.** `GradScaler` skips silently; `register_step_post_hook` tells you whether `step()` ran; only a parameter delta tells you whether anything changed. Gate the scheduler on the second.\n- **`grad is None` and `grad == 0` are different** to the optimizer. One is skipped, the other is processed and may still move.\n- **A bad loss cannot have been caused by the optimizer step that follows it.** Inspect the state entering that forward — parameters, mutable buffers, optimizer and resume context, stochastic state — and the batch being evaluated. Which is only a useful fork if enough was kept to reconstruct both.\n\nIf one sentence survives: *the loss curve is a lossy view of a stateful transition — record enough to reconstruct the transition, and the spike stops being a mystery.*\n\n## Where this goes next\n\nThe instability discussed here is mostly about state and control flow. For the arithmetic underneath it — where the non-finite values are actually born, and why a mathematically correct formula returns the wrong answer — see [numerical stability](../tensors/04-numerical-stability.qmd). For the optimizer internals this chapter assumes, [optimizers from scratch](05-optimizers-from-scratch.qmd) derives the moments and the decoupling that makes `AdamW` different from Adam with L2.\n\n## References\n\n- [`torch.optim.Optimizer.zero_grad`](https://pytorch.org/docs/stable/generated/torch.optim.Optimizer.zero_grad.html) — the `set_to_none` default and its semantics.\n- [`torch.nn.utils.clip_grad_norm_`](https://pytorch.org/docs/stable/generated/torch.nn.utils.clip_grad_norm_.html) — total-norm computation, in-place modification, `error_if_nonfinite`.\n- [`torch.optim.Optimizer.register_step_post_hook`](https://pytorch.org/docs/stable/generated/torch.optim.Optimizer.register_step_post_hook.html) — the executed-step signal; it runs after `step()`, which is not the same as a parameter having changed.\n- [Automatic Mixed Precision examples](https://pytorch.org/docs/stable/notes/amp_examples.html) — `unscale_` ordering, skipped steps, per-optimizer behaviour.\n- [`FullyShardedDataParallel`](https://pytorch.org/docs/stable/fsdp.html) — why sharded models need FSDP's own gradient clipping.\n- Kingma and Ba, [*Adam: A Method for Stochastic Optimization*](https://arxiv.org/abs/1412.6980), 2015 — the moment estimates and bias correction referenced throughout.\n\n",
    "supporting": [
      "07-your-loss-spiked_files"
    ],
    "filters": [],
    "includes": {}
  }
}